Feature/api/code number confirmation
ufersa/plataforma-sabia pull request #1023
Opened 2021-04-28 23:39 UTC by alexandreadames

## Summary

Resolves #1011 

## Relevant technical choices

As seguintes operações são confirmadas por geração de código único, ex 786631:

1. Confirmação de conta (Após o registro)
2. Alteração de senha (Esqueceu a senha)
3. Mudança de email (No perfil)

O sistema gera o código e envia para o email do usuário, o sistema precisa chamar as rotas de confirmação passando esse token e o email do usuário por segurança.

## Rotas alteradas

| Description | Method | Route | Body/Query | Auth |
| --- | --- | --- | --- | --- |
Confirms User Account | POST |/auth/confirm-account |email, token, scope | NO | 
Resets User Password | POST |/auth/reset-password |email, token, password | NO | 
Confirms User Email | PUT |/user/change-email |email, token, scope | NO | 

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2021-05-06 11:26 UTC, nichollasrennah commented
@mateus4k você revisou essa PR?

2021-05-08 05:46 UTC, mateus4k commented
@alexandreadames, o teste e2e que não está passando é um comportamento esperado, certo?

2021-05-08 07:17 UTC, mateus4k reviewed
Bom trabalho! 💯  

O teste e2e que não está passando é um comportamento esperado, certo? Se sim, podemos dar um `skip` neste teste por enquanto?

2021-05-08 07:17 UTC, mateus4k commented on packages/api/app/Models/Token.js
> +	}
O que acha da implementação abaixo? Creio que ficou mais fácil de entender e, mudando o min/max de lugar evitamos recriá-los a cada iteração 
```suggestion
	static async generateUniqueTokenCode() {
		const min = 100000;
		const max = 999999;
		
		while(true) {
			const generatedCode = Math.floor(Math.random() * (max - min + 1)) + min;
			// eslint-disable-next-line no-await-in-loop
			if (!await this.findBy('token', generatedCode)) {
				return generatedCode;
			}
		}
	}
```

2021-05-08 07:17 UTC, mateus4k commented on packages/api/app/Models/User.js
> +						password: crypto.randomBytes(12).toString('hex'),
💯

2021-05-08 13:02 UTC, alexandreadames commented
> Bom trabalho! 💯
> 
> O teste e2e que não está passando é um comportamento esperado, certo? Se sim, podemos dar um `skip` neste teste por enquanto?

É esperado, falta adaptar o front web. Seria interessante usar essa mesma PR.

2021-05-08 13:26 UTC, alexandreadames commented on packages/api/app/Models/Token.js
> +	}
> O que acha da implementação abaixo? Creio que ficou mais fácil de entender e, mudando o min/max de lugar evitamos recriá-los a cada iteração

Dá certo!

2021-05-08 17:36 UTC, mateus4k submitted a review, later dismissed
@nichollasrennah, agora precisamos fazer a feature no frontend. Se possível, vamos continuar usando essa PR pra isso pra que não tenhamos o perigo de subir somente a API para produção e acabar quebrando a plataforma.

2021-05-08 18:25 UTC, nichollasrennah commented
Sim. Davi está trabalhando nela agora.

Em sáb., 8 de mai. de 2021 14:37, Mateus Sampaio ***@***.***>
escreveu:

> ***@***.**** approved this pull request.
>
> @nichollasrennah <https://github.com/nichollasrennah>, agora precisamos
> fazer a feature no frontend. Se possível, vamos continuar usando essa PR
> pra isso pra que não tenhamos o perigo de subir somente a API para produção
> e acabar quebrando a plataforma.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ufersa/plataforma-sabia/pull/1023#pullrequestreview-655009503>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALO7O33SJFRCBHQCHXODLM3TMVZEBANCNFSM43YBDKYA>
> .
>

2021-05-08 18:28 UTC, mateus4k commented
cc @davioliveiira

2021-05-08 20:21 UTC, luizeboli commented
Só uma dúvida por curiosidade,  pouco provável que isso aconteça cedo, mas se esgotar todos os tokens?  De 100000 a 999999?

Pelo o que vi, ao gerar o token o While checa se ele já existe, mas não relaciona o token ao usuário. Está correto? Por exemplo, teria problema o usuário X ter o token 123456 e o usuário Y também?

2021-05-09 12:11 UTC, mateus4k commented
Excelente observação, @luizeboli!

Sobre o limite de tokens, precisamos implementar um `where` nessa query para que busquemos somente os tokens com determinado limite de criação, por exemplo:
```js
Tokens
  .query()
  .where('token', generatedCode)
  .where('created_at', '>=', dayjs().subtract(3, 'days'))
  .first();
```

Também acho que seria interessante mover essas regras de negócio para a camada configuração. Exemplo:
```js
// config/app.js
token: {
  // Verification token lifetime in days
  ttl: 3,
  // Token value range
  range: {
    min: 100000,
    max: 999999,
  }
}
``` 
Assim, facilitaria bastante caso precisarmos alterar essas regras 🙂

2021-05-11 22:32 UTC, davioliveiira approved these changes

2021-05-11 22:40 UTC, mateus4k commented on packages/api/app/Models/Token.js
> +					.subtract(ttl, 'hour')
Oops
```suggestion
					.subtract(ttl, 'days')
```

2021-05-11 22:43 UTC, mateus4k commented on packages/api/app/Models/Token.js
> +	static verifyIfTokenExists(generatedCode) {
O que acha de modificar o nome para algo como `getByCode` para ser mais claro?

2021-05-11 22:43 UTC, mateus4k commented on packages/api/app/Models/Token.js
> +					.subtract(ttl, 'hour')
```suggestion
					.subtract(ttl, 'days')
```

2021-05-11 22:56 UTC, mateus4k reviewed
Pode confirmar se nesse trecho de código precisaremos atualizar algo ou se ele ainda será necessário?
Se não me engano o `scope`, por exemplo, não é mais utilizado
https://github.com/ufersa/plataforma-sabia/blob/cb6f7bfd08e607c11efddffeb0599ccfa3858249/packages/web/pages/index.js#L104-L111

2021-05-11 22:56 UTC, mateus4k commented on packages/web/components/Modal/ForgotPasswordModal/index.js
> +		closeModal();
A variável `message` é exibida dentro do modal caso o `result` seja falsy, então, devemos fechar o modal somente caso a requisição dê certo

2021-05-11 22:56 UTC, mateus4k commented on packages/web/services/auth.js
> +		.catch(() => false);
Seria bacana retornar a mensagem de erro que a API retornar 🤔

2021-05-11 22:58 UTC, davioliveiira commented on packages/web/components/Modal/ForgotPasswordModal/index.js
> +		closeModal();
@mateus4k nesse caso aqui não temos mais essa mensagem sendo exibida no modal, pois agora jogamos o usuário direto para a página de alterar senha para inserir `email, token e senha`. Ah e o toast que fica encarregado de mostrar a mensagem

2021-05-12 18:22 UTC, luizeboli commented on packages/web/services/auth.js
> +export async function resetPassword(token, password, email) {
Não precisa do async se está usando Promise.then

2021-05-12 18:22 UTC, luizeboli commented on packages/web/services/auth.js
> +export async function accountConfirmation(token, email) {
Também não precisa do async

2021-05-12 18:26 UTC, luizeboli commented on packages/web/components/Modal/ForgotPasswordModal/index.js
> +			router.push('/auth/confirm-account');
Existe um arquivo de constantes para as urls das páginas (consts/pages), pode consumir através dele para centralizarmos

2021-05-12 18:26 UTC, luizeboli commented on packages/web/components/Modal/LoginModal/index.js
> +				<StyledLink href="/auth/confirm-account">Confirmar conta</StyledLink>
Aqui tbm.

2021-05-12 18:26 UTC, luizeboli commented on packages/web/components/Modal/RegisterModal/index.js
> +			router.push('/auth/confirm-account');
Aqui tbm.

2021-05-12 18:27 UTC, luizeboli commented on packages/web/pages/auth/confirm-account.js
> +				redirectTo: '/',
Aqui tbm.

2021-05-12 18:28 UTC, luizeboli requested changes
Fiz alguns comentários referentes ao web :)

2021-05-13 22:30 UTC, mateus4k commented on packages/web/services/auth.js
> +		.catch(() => false);
Sabe dizer se a API pode retornar algum erro nesta rota, @alexandreadames?

2021-05-13 22:31 UTC, mateus4k commented on packages/api/app/Models/Token.js
> +					.subtract(ttl, 'hour')
Se lembra de atualizar aqui antes do merge, @alexandreadames

2021-05-14 18:52 UTC, luizeboli submitted a review, later dismissed
A parte do web pra mim ta ok 👍🏻

2021-05-14 21:29 UTC, mateus4k commented
Restam somente alguns ajustes da parte da API 🙂 
https://github.com/ufersa/plataforma-sabia/pull/1023#discussion_r630585690

2021-05-14 21:30 UTC, mateus4k requested changes
Restam somente alguns ajustes na parte da API 🙂
https://github.com/ufersa/plataforma-sabia/pull/1023#discussion_r630585690

2021-05-20 00:38 UTC, mateus4k reviewed
Show!

2021-05-20 00:38 UTC, mateus4k commented on packages/api/test/functional/auth.spec.js
> +		.subtract(4, 'days')
Aqui seria bacana trocar pelo `ttl + 1`, assim, caso o `ttl` mude, não quebrará a função 🙂 
```suggestion
		.subtract(Config.get('app.ttl') + 1, 'days')
```

2021-05-20 22:57 UTC, mateus4k approved these changes

2021-05-20 22:58 UTC, merged