Lists all users in responsible technology tab order ASC
ufersa/plataforma-sabia pull request #1042
Opened 2021-05-15 16:32 UTC by alexandreadames

## Summary

Resolves #1022 

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2021-05-15 22:56 UTC, mateus4k commented on packages/api/app/Middleware/HandleParam.js
> +		const maxPerPage = 1000;
:eyes:

2021-05-16 14:55 UTC, mateus4k requested changes

2021-05-16 14:55 UTC, mateus4k commented on packages/api/app/Middleware/HandleParam.js
> +		const maxPerPage = 1000;
Não podemos fazer isso. Liberaria todo o servidor a processar requests gigantescas.

2021-05-16 14:55 UTC, mateus4k commented on packages/admin/src/pages/technologies/Form/ResponsibleForm.js
> +						perPage={1000}
Ao invés disso, precisamos utilizar paginação/pesquisa para ter acesso a todos os itens

2021-05-27 12:16 UTC, nichollasrennah commented
Como tá essa PR, @alexandreadames ?

2021-06-05 11:46 UTC, mateus4k approved these changes
Para fazer após a paginação do select: #1055 🙂

2021-06-05 17:16 UTC, merged