Query Param filterBy
ufersa/plataforma-sabia pull request #1103
Opened 2021-07-02 14:24 UTC by alexandreadames

## Summary

Resolves #1062 

## Relevant technical choices

In all endpoints, was added the query param: `filterBy` and `filter`, ex

`GET institutions?filterBy=name&filter=pw`

`filterBy`: Collumm in database
`filter`: value to search

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2021-07-02 16:25 UTC, mateus4k submitted a review, later dismissed

2021-07-02 16:26 UTC, mateus4k commented
Se puder cobrir por testes acho que seria uma boa também

2021-07-02 17:09 UTC, luizeboli commented on packages/api/app/Models/Traits/Params.js
> +				this.where(filterBy, 'LIKE', `${filter}%`);
```suggestion
				this.where(filterBy, 'LIKE', `%${filter}%`);
```

2021-07-03 18:24 UTC, mateus4k approved these changes

2021-07-05 19:35 UTC, luizeboli approved these changes

2021-07-05 19:36 UTC, luizeboli requested changes

2021-07-05 19:36 UTC, luizeboli commented on packages/api/app/Models/Traits/Params.js
> +		}; */
```suggestion
```

2021-07-05 19:37 UTC, luizeboli requested changes

2021-07-05 19:37 UTC, luizeboli commented on packages/api/app/Models/Traits/Params.js
> +
```suggestion
```

2021-07-07 21:28 UTC, luizeboli submitted a review, later dismissed

2021-07-07 21:58 UTC, mateus4k submitted a review, later dismissed

2021-07-08 12:33 UTC, mateus4k approved these changes
Nice!

2021-07-08 13:53 UTC, merged