mobile adjustment
ufersa/plataforma-sabia pull request #1119
Opened 2021-07-15 22:39 UTC by andreluizlq

## Summary

Resolves #

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2021-07-16 11:30 UTC, luizeboli commented
@andreluizlq você acabou excluindo o .env.example do web e alterando o package-lock da api, sendo que não havia necessidade.

Consegue reverter essas alterações?

Outro detalhe, eu não tenho certeza se essa modificação que vc fez irá resolver o problema que o @nichollasrennah reportou, pelo fato de estarmos usando posicionamento absoluto. Seria legal pedir pra ele testar antes de concluir 👍🏻

2021-07-16 11:30 UTC, luizeboli requested changes
Fiz alguns comentários acima 👍🏻

2021-07-16 17:29 UTC, andreluizlq commented
Corrigido @luizeboli, esperar só @nichollasrennah  ver a questão da imagem com o teclado.

Antes:
![WhatsApp Image 2021-07-16 at 13 11 25](https://user-images.githubusercontent.com/38213016/125986184-8d0a3d54-305c-4d9b-8d13-ed75a70eb5ff.jpeg)

Depois:
![WhatsApp Image 2021-07-16 at 13 23 37](https://user-images.githubusercontent.com/38213016/125986240-34d0c6ab-1a64-41b4-a83e-bc7f48519e8d.jpeg)

2021-07-30 13:45 UTC, mateus4k approved these changes

2021-08-04 13:25 UTC, merged