feature/admin/crud-taxonomy-admin
ufersa/plataforma-sabia pull request #278
Opened 2020-06-30 14:19 UTC by NaylsonFerreira

## Summary

Resolves #58 

## Relevant technical choices

## QA Steps
- [x] CRUD Taxonomias
- [x] Visualizar os termos associados as Taxonomias
- [x] CRUD Termos
- [x] Associar termos a uma tecnologia 

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [X] My code has an appropriate set of unit tests which all pass.
- [X] My code passes the linting.
- [X] My code has proper inline documentation.
- [X] I have manually tested this PR.

2020-07-03 19:05 UTC, nicholasio commented on packages/admin/src/pages/technologies/list.js
> +			<TextField source="description" />
Na listagem não precisamos exibir todos os campos, fica muita informação na tela.]

Vamos exibir somente:

- id
- title
- thumbnail
- status
- terms

2020-07-03 19:07 UTC, nicholasio commented on packages/admin/src/pages/technologies/Form/index.js
> +		<TextInput source="contribution" fullWidth resettable />
```suggestion
		<TextInput source="primary_purpose" fullWidth resettable multiline  />
		<TextInput source="secondary_purpose" fullWidth resettable multiline  />
		<TextInput source="application_mode" fullWidth resettable multiline  />
		<TextInput source="application_examples" fullWidth resettable multiline  />
		<TextInput source="installation_time" fullWidth resettable multiline  />
		<TextInput source="solves_problem" fullWidth resettable multiline  />
		<TextInput source="entailes_problem" fullWidth resettable multiline  />
		<TextInput source="requirements" fullWidth resettable multiline  />
		<TextInput source="risks" fullWidth resettable multiline />
		<TextInput source="contribution" fullWidth resettable multiline  />
```

2020-07-03 19:08 UTC, nicholasio commented on packages/admin/src/pages/technologies/Form/index.js
> +		<TextInput source="status" fullWidth resettable />
Aqui é pra ser um dropdown com os status possíveis no sistema.

Os status possíveis podem ser "hardcoded" mesmo aqui. Cria um array com os valores que a API aceita e passa pro component dropdown do react admin.

2020-07-03 19:08 UTC, nicholasio commented on packages/admin/src/pages/technologies/Form/index.js
>  		<TextInput source="status" fullWidth />
Este campo está duplicado.

2020-07-03 19:10 UTC, nicholasio commented on packages/admin/src/pages/technologies/Form/index.js
> +		<ReferenceArrayInput label="Terms" source="terms" reference="terms" fullWidth perPage={999}>
Os termos da taxonomia não será tão fácil assim... pois fica confuso do jeito que está... Nós precisamos agrupar os termos de acordo com sua taxonomia.

Acho que podemos fazer um MultiSelect para cada taxonomia cadastrada no banco. Você precisa bolar uma forma de implementar isso no react admin.

Da forma que está tem dois problemas:

1. Não dá pra saber a qual taxonomia cada termo pertence.
2. Ao longo do tempo essa lista vai ficar muito grande para exibir todos os termos de todas as taxonomias.

2020-07-03 19:13 UTC, nicholasio commented on packages/admin/src/pages/technologies/Form/index.js
> +		<ReferenceArrayInput label="Terms" source="terms" reference="terms" fullWidth perPage={999}>
Podemos usar o `SelectArrayInput` e `ReferenceArrayInput` para cada taxonomia. O detalhe é que precisa ter um para cada taxonomia e o ideal é que eles sejam dinâmicos.

2020-07-03 19:14 UTC, nicholasio commented on packages/admin/src/pages/technologies/Form/index.js
> +		<ReferenceArrayInput label="Terms" source="terms" reference="terms" fullWidth perPage={999}>
![select-array-input](https://user-images.githubusercontent.com/6104632/86493542-4e77f200-bd48-11ea-9386-40501e5302cc.gif)

2020-07-07 16:41 UTC, NaylsonFerreira commented on packages/admin/src/providers/dataProvider.js
> +			const NumTotalTaxonomias = 15;
@nicholasio  aqui consigo enviar o numero total de taxonomias pelo `params.data` , não seria necessário esse valor fixo de 15, mas no `create`  não encontrei uma forma de pegar esse valor dinamicamente. tem uma sugestão ?

2020-07-13 10:17 UTC, nicholasio commented
@NaylsonFerreira a parte das taxonomias separadas ficou bom. Mas eu notei um erro quando eu salvo, os dados estão sendo salvos mas ele buga o react-admin até que eu faça um hard refresh.

Vou olhar com mais calma essa PR aqui mas acho que estamos bem próximos.

2020-07-15 18:18 UTC, NaylsonFerreira commented
Isso é um problema relatado em https://github.com/marmelab/react-admin/issues/2694

2020-10-04 16:42 UTC, NaylsonFerreira commented
Tá quebrado, vou olhar novamente.

2020-10-06 12:32 UTC, NaylsonFerreira commented
Falta um ajuste

2020-10-06 13:28 UTC, NaylsonFerreira commented
@nicholasio  aqui está pronto pra revisão.

2020-10-09 13:34 UTC, luizeboli requested changes
Muito bom @NaylsonFerreira 🎉

Fiz algumas sugestões, uma delas considero mais importante que é a questão da imutabilidade.

----

Fazendo alguns testes na tela cheguei a alguns pontos, uns são erros e outros são detalhes que podem melhorar a usabilidade. Vi também que foram coisas não específicas desse PR, mas pertencem a esse contexto:

1 - Ambos os campos do cadastro são obrigatórios mas se eu preencher apenas um deles o botão fica habilitado: 

![image](https://user-images.githubusercontent.com/13091635/95588095-5a471480-0a19-11eb-893f-4f2f74757564.png)

2 - O botão de salvar desse mesmo form não dá feedback visual pro usuário de que algo está acontecendo na aplicação. Poderíamos inserir um spinner ou desabilitar o botão.

![Oct-09-2020 10-25-36](https://user-images.githubusercontent.com/13091635/95588713-20c2d900-0a1a-11eb-8655-1f27fe774ac8.gif)
 
3 - Tem um comportamento um tanto estranho acontecendo: Se eu editar uma taxonomia, e remover a descrição, a tela permite salvar, volta pra lista com um snackbar informando que o elemento foi atualizado, porém a request falha com um erro de `The taxonomy has already been taken by someone else.``

2020-10-09 13:34 UTC, luizeboli commented on packages/admin/src/providers/dataProvider.js
> +
Assim funciona tbm e fica mais organizado

```suggestion
		const query = {
			page,
			perPage,
			order,
			orderBy: field,
			embed: params.embed ? '' : undefined,
		};

```

2020-10-09 13:34 UTC, luizeboli commented on packages/admin/src/components/ReferenceArrayField.js
> +		record[source] = record[source].map((i) => i.id || i);
Podemos tentar trabalhar com a imutabilidade aqui.

```suggestion
		const newRecord = { ...record, [source]: record[source].map((i) => i.id || i) }
```

2020-10-09 16:10 UTC, NaylsonFerreira commented on packages/admin/src/pages/roles/Form/index.js
> +			perPage={999}
Boa!
vou remover e deixar padrão.

2020-10-09 17:02 UTC, NaylsonFerreira commented on packages/admin/src/providers/dataProvider.js
> +
Feito!

2020-10-09 17:05 UTC, NaylsonFerreira commented on packages/admin/src/components/ReferenceArrayField.js
> +		record[source] = record[source].map((i) => i.id || i);
Não consegui fazer essa sugestão funcionar

2020-10-09 17:12 UTC, luizeboli commented on packages/admin/src/components/ReferenceArrayField.js
> +		record[source] = record[source].map((i) => i.id || i);
Eu acabei não fazendo isso no PR, mas, vc chegou passar esse `newRecord` pro componente no lugar do `record`? Eu fiz aqui e foi de boa

2020-10-09 18:28 UTC, NaylsonFerreira commented on packages/admin/src/components/ReferenceArrayField.js
> +		record[source] = record[source].map((i) => i.id || i);
Funcionou!

2020-10-09 21:30 UTC, luizeboli submitted a review, later dismissed

2020-10-10 20:41 UTC, lcnogueira commented
@NaylsonFerreira , eu percebi que consigo associar um termo a uma taxonomia no momendo do cadastro do termo. Porém, eu não consigo associá-lo se eu pegar uma taxonomia já existente e tentar alterá-la. Já havia percebido?

2020-10-11 21:36 UTC, NaylsonFerreira commented on packages/admin/src/pages/terms/Form/index.js
> +			perPage={100}
@luizeboli  aqui precisamos do perPage para listar todas as Taxonomias no select

2020-10-11 21:38 UTC, NaylsonFerreira commented
> @NaylsonFerreira , eu percebi que consigo associar um termo a uma taxonomia no momendo do cadastro do termo. Porém, eu não consigo associá-lo se eu pegar uma taxonomia já existente e tentar alterá-la. Já havia percebido?

Bem notado @lcnogueira. A API esperava `taxonomyId` ao invés de `taxonomy_id`

2020-10-12 14:28 UTC, luizeboli approved these changes

2020-10-12 14:28 UTC, luizeboli commented
Bom trabalho 😁

2020-10-13 00:38 UTC, lcnogueira approved these changes
Bom trabalho, Naylson 👍 💯

2020-10-13 12:47 UTC, merged