Detalhamento de Tecnologias - Relatos de Experiência
ufersa/plataforma-sabia pull request #373
Opened 2020-08-29 03:24 UTC by mateus4k

## Summary

Resolves #215

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2020-09-06 19:58 UTC, mateus4k commented on packages/web/components/Technology/Details/Tabs/index.js
> +	];
Abstraí a orquestração de tabs para este componente. Assim, ficará mais simples e organizado, semelhante ao que foi feito nos steps de nosso `FormWizard`.

@marcusmota, essa é a adaptação que precisará fazer quando submeter a issue #217.

2020-09-06 20:19 UTC, mateus4k commented
@nicholasio, alguns detalhes a serem observados sobre a nova tab:

- Acabei deixando o select do html na ordenação de revisões. Como @calaca está fazendo modificações no select que já temos integrado ao form, creio que não seja bom fazer agora aquela refatoração para termos um select personalizado independente do form. Por conta do tempo de entrega desta tarefa, podemos abrir uma nova issue para substituir este select por um personalizado?

- A ordenação não está funcionando do lado da api mas já temos uma issue aberta para isso (#386).

- Teremos necessidade de paginação aqui. Há outro local em que isso já feito no front? Se não, fica para outra issue a sua implementação nessa tab ou faço nessa mesmo? Lembrando que na api também não está funcionando por conta do resource não ser o primeiro item da URL :sweat_smile:

2020-09-07 12:39 UTC, nicholasio requested changes

2020-09-07 12:39 UTC, nicholasio commented on cypress/e2e/web/technologyDetails.js
> +			cy.findByTestId('image')
Precisamos ter cuidado com o `testId` a ideia do testId é usar quando é difícil fazer a query por outros meios. A filosofia dos testes deve ser "procurar pelo que o usuário procuraria". A medida que vamos adicionando testIds em todos os lugares ficamos cada vez mais dependentes da implementação.

Na maioria das vezes o ideal é fazer `getByRole` e `getByTest`

2020-09-07 12:39 UTC, nicholasio commented on packages/web/__tests__/pages/t/index.js
> +			<Page technology={technology} relatedTechnologies={[{ ...technology }]} />,
```suggestion
			<Page technology={technology} relatedTechnologies={[ technology ]} />,
```

2020-09-07 12:39 UTC, nicholasio commented on packages/web/components/Technology/Details/Header.js
> +						<Likes technology={technology.id} count={technology.likes} />
`technology` pode dar a entender que estamos passando toda o objeto da tecnologia. Além disse os `likes` pode ser um component mais genérico. Sugiro renomear simplesmente para `id`.

2020-09-07 12:39 UTC, nicholasio commented on packages/web/components/Technology/Details/Header.js
> +						<Likes technology={technology.id} count={technology.likes} />
```suggestion
						<Likes id={technology.id} count={technology.likes} />
```

2020-09-07 12:39 UTC, nicholasio commented on packages/web/components/Technology/Details/Tabs/Attachments.js
> +const Description = () => {
Acho que esqueceu de renomear esse componente aqui

2020-09-07 12:39 UTC, nicholasio commented on packages/web/components/Technology/Details/Tabs/Costs.js
> +const Description = () => {
Again

2020-09-07 12:39 UTC, nicholasio commented on packages/web/components/Technology/Details/Tabs/Review/index.js
> +const Review = () => {
Me parece uma ótima oportunidade para usar o `https://swr.vercel.app/`

2020-09-07 12:39 UTC, nicholasio commented on packages/web/components/Technology/Details/Tabs/Review/index.js
> +const Review = () => {
`useSWR('key', getReviews, { initialData: technology.reviews })`

2020-09-07 12:39 UTC, nicholasio commented on packages/web/components/Technology/Details/Tabs/Review/index.js
> +const Review = () => {
FYI: nunca usei mas tem algumas features interessantes, acho que seria uma boa adotar essa lib para quando precisarmos fazer client-side data fetching.

@ufersa/front-end-team

2020-09-07 13:35 UTC, mateus4k commented on cypress/e2e/web/technologyDetails.js
> +			cy.findByTestId('image')
Tem razão. Essa implementação fiz há um certo tempo atrás e lembro que foi complicado de acessar por outros meios, por isso recorri ao data attribute. Vou evitá-los ainda mais agora!

2020-09-07 17:21 UTC, mateus4k commented on packages/web/components/Technology/Details/Tabs/Review/index.js
> +const Review = () => {
É uma boa ideia! Gastei um tempo tentando adaptar, porém, não consegui utilizá-lo junto aos nossos services. Abri uma discussion (https://github.com/vercel/swr/discussions/639) pra ver se alguém dá uma luz sobre a utilização. Só consegui utilizar passando o endpoint hardcoded, deixando o service sem utilidade :confused:

2020-09-07 17:39 UTC, nicholasio commented on packages/web/components/Technology/Details/Tabs/Review/index.js
> +const Review = () => {
mas o service seria a função `fetcher`. Além disso podemos criar uma versão do service como um custom hook.

2020-09-07 19:53 UTC, mateus4k commented on packages/web/components/Technology/Details/Tabs/Review/index.js
> +const Review = () => {
Vacilo meu :sweat_smile:. Fiz o consumo do service normalmente.

https://github.com/ufersa/plataforma-sabia/blob/526746d0bb95153ac89d286e506613c61f9b56e7/packages/web/components/Technology/Details/Tabs/Review/index.js#L40-L46

2020-09-07 22:31 UTC, nicholasio requested changes
Só mais algumas observações 👍

2020-09-07 22:31 UTC, nicholasio commented on packages/web/components/Loading/__tests__/index.js
> +		expect(container.querySelector('h1').textContent).toEqual(childrenText);
É mais interessante usar as queries to react-testing-library, melhora as asserções e evita ter que ficar fazendo `querySelector` e usando `textContent` 

E.g `expect(screen.getByRole('heading')).toHaveTextContent(childrenText)`

Dessa forma quando o teste falhar o jest vai informar que o `textContent` não está sendo o valor esperado, no lugar de uma mensagem genérica.

2020-09-07 22:31 UTC, nicholasio commented on packages/web/components/Technology/Details/Tabs/Review/index.js
> +	const selectOptions = useMemo(() => {
Otimização desnecessária :).

A solução aqui é mover esse array para fora do componente. Ele não tem nenhuma dependência de props.

2020-09-07 22:31 UTC, nicholasio commented on packages/web/components/Technology/Details/Tabs/Review/index.js
> +	const getOrderValue = useCallback((raw) => {
Mesma observação do comentário anterior, defina essa função fora do componente e você não precisará do `useCallback`.

2020-09-07 22:31 UTC, nicholasio commented on packages/web/components/Technology/Details/Tabs/Review/index.js
> +		[technology.id, ordering],
Acho que só `[tecnology.id, ordering]` não será suficiente como key, pois esse conjunto de valores pode ser usado como key para outra coisa.

Precisamos de algo como `['getReviews', technology.id, ordering]`

2020-09-09 03:19 UTC, nicholasio approved these changes

2020-09-09 03:19 UTC, merged