Hotfix/web/register-tech
ufersa/plataforma-sabia pull request #392
Opened 2020-09-06 20:26 UTC by calaca

## Summary

Resolves #389

## Relevant technical choices

Foi efetuado o conserto dos bugs listados na issue acima bem como a criação de um novo componente para lidar com máscara de moeda.

**PS:** Existe um vídeo compartilhado no canal do pacote web do projeto com mais detalhes sobre o último item da lista da issue.

## QA Steps

Verificar se os ajustes visuais listados na issue estão presentes.

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2020-09-06 20:55 UTC, lcnogueira commented
@calaca , percebi aqui que pelo menos um teste e2e quebrou. Você chegou a investigar o motivo? Pelo que vi rapidamente, com a mudança, tem algum trecho que o cypress não está conseguindo mais pegar. É algo justamente relacionado àquele campo de valor em moeda. Consegue verificar? Se precisar de ajuda, só mandar :+1:

2020-09-07 02:21 UTC, calaca commented
@lcnogueira Realmente! Mudei algumas coisas e esqueci de checar os testes E2E. Alguns testes do Jest também estavam quebrando e consertei.

Achei estranho que na aba de commits do PR não aparecem as alterações que fiz consertando os testes. Essa informação só aparece aqui na aba de conversa.

2020-09-07 12:57 UTC, nicholasio requested changes
Muito bom! Notei um pequeno detalhe e deixei algumas sugestões.

Vou tentar olhar esse problema do novo component que você criou.

Notei um problema em resoluções menores no select.

![image](https://user-images.githubusercontent.com/6104632/92389637-d505d280-f0ef-11ea-84d6-afee0c1e1e64.png)

Talvez possamos aumentar o `height` de todos os inputs um pouco para dar um pouco mais de espaço, ou tratar o select input em telas menores.

2020-09-07 12:57 UTC, nicholasio commented on packages/web/components/Form/__tests__/CurrencyInputField.js
> +	expect(container.querySelector('input[name=price]')).toHaveValue('R$ 1.000,50');
É sempre bom evitar fazer queries pelo `container`. Nesse caso você pode usar o `getByRole` https://testing-library.com/docs/guide-which-query

2020-09-07 12:57 UTC, nicholasio commented on packages/web/components/Form/__tests__/CurrencyInputField.js
> +	fireEvent.submit(container.querySelector('form'));
Ver meu comentário anterior sobre evitar `container.querySelector`

2020-09-07 12:57 UTC, nicholasio commented
Tem uns snapshots falhando ainda.

2020-09-07 13:54 UTC, calaca commented
@nicholasio obrigada pelo review!

Removi os selectors e passei a utilizar `getByLabelText` e `getByTestId` (vi que o test id deve ser o último recurso mas não encontrei outro meio de selecionar o form que não fosse assim).

Sobre o problema que vc notou no select, consegui resolver fácil. Foi só trocar o `height` fixo por um `min-height`:
![image](https://user-images.githubusercontent.com/10481028/92392965-7e02fc00-f0f5-11ea-9e67-0f446066ddad.png)
![image](https://user-images.githubusercontent.com/10481028/92392995-89eebe00-f0f5-11ea-841a-cb559e9a3e2e.png)

Já sobre os snapshots falhando: isso ocorre pois eles estão desatualizados. Rodei o comando `npm run jest -- -u` para atualizar no local e tudo passa corretamente. Porém parece que o CI não faz isso. Inclusive tem esse log no processo de build do CI:
![image](https://user-images.githubusercontent.com/10481028/92394338-c02d3d00-f0f7-11ea-894a-3dd591c4303d.png)

Resultados do `npm run jest` no meu local:
![image](https://user-images.githubusercontent.com/10481028/92394637-434e9300-f0f8-11ea-9395-a8fa6e6a9f4e.png)
![image](https://user-images.githubusercontent.com/10481028/92394606-3762d100-f0f8-11ea-87ff-db09e5f74133.png)

O que estou fazendo de errado?

2020-09-07 13:56 UTC, nicholasio commented
@calaca vc precisa atualizar os snapshots e comittar eles. Os snapshots fazem parte do repositório.

2020-09-07 13:58 UTC, calaca commented
@nicholasio mas eu já fiz isso e aqui está passando tudo. Não estou conseguindo identificar o erro.

2020-09-07 14:03 UTC, lcnogueira commented
@calaca , em relação aos commits, aparece aqui pra mim na aba de commit também :thinking: .

Em relação aos snapshots, faz um teste: atualiza tua branch local com o código da master e roda novamente os snapshots pra ver se continuam passando ou se falham...lembro que já tive esse problema.

2020-09-07 14:21 UTC, calaca commented
@lcnogueira fiz o rebase. Os testes passam localmente mas continuam falhando no CI. Todos os erros são em relação a formatação de moeda:
![image](https://user-images.githubusercontent.com/10481028/92396406-557e0080-f0fb-11ea-81f3-b6eea810155d.png)
Parece que o CI está pegando as formatações no padrão internacional e não brasileiro mesmo os testes e componentes estando configurados no padrão brasileiro.

2020-09-07 14:33 UTC, calaca commented
@lcnogueira @nicholasio conseguem rodar os testes dessa branch na máquina de vcs, por favor? Só para confirmar se é alguma configuração no CI que está sempre indo para o padrão internacional.

2020-09-07 16:08 UTC, nicholasio requested changes

2020-09-07 16:08 UTC, nicholasio commented on packages/web/components/Form/CurrencyInputField.js
> +const CurrencyInputField = ({ currency, name, defaultValue, ...inputFieldProps }) => {
Sei que já aprovei mas acabei de notar que podemos remover essa prop currency e simplesmente respeitar o idioma atual.

Veja aqui para pegar o idioma corrente. https://github.com/ufersa/plataforma-sabia/blob/master/packages/web/components/Header/LanguageSwitcher.js#L24

Dessa forma, na hora que o usuário altera o idioma, o componente aqui já vai ser alterado.

2020-09-07 18:10 UTC, calaca commented on packages/web/components/Form/CurrencyInputField.js
> +const CurrencyInputField = ({ currency, name, defaultValue, ...inputFieldProps }) => {
Ajuste feito!

Queria testar também o componente quando o idioma é alterado. Pesquisei aqui mas não encontrei como fazer o mock ou simular essa alteração. Tem alguma ideia de como posso fazer isso?

Sabendo como simular essa alteração de idiomas posso alterar o componente Price para capturar o locale do i18n também.

2020-09-07 19:37 UTC, mateus4k commented on packages/web/components/Form/SwitchField.js
> +						<p>{isChecked ? 'Sim' : 'Não'}</p>
Esse aqui já temos nos locales:
```suggestion
						<p>{isChecked ? t('common:yes') : t('common:no')}</p>
```

2020-09-07 19:40 UTC, mateus4k commented on packages/web/package.json
> +    "jest:visual": "NODE_ICU_DATA=node_modules/full-icu jest -c tests/visual/jest.config.js",
Será que não dá pra mover o `NODE_ICU_DATA=node_modules/full-icu` para o `setupTests`? :thinking:

2020-09-07 19:43 UTC, mateus4k submitted a review, later dismissed

2020-09-07 21:58 UTC, calaca commented on packages/web/components/Form/SwitchField.js
> +						<p>{isChecked ? 'Sim' : 'Não'}</p>
Fica bem melhor com o locale mesmo mas tenho pouca experiência com testes e não consegui encontrar uma forma de fazer um mock que renderize as traduções.

2020-09-07 22:33 UTC, nicholasio commented on packages/web/components/Form/SwitchField.js
> +						<p>{isChecked ? 'Sim' : 'Não'}</p>
@calaca Nos testes as traduções estão mockadas para renderizar o slug. Não precisa renderizar a tradução em si :).

2020-09-07 22:35 UTC, nicholasio commented on packages/web/components/Form/CurrencyInputField.js
> +const CurrencyInputField = ({ currency, name, defaultValue, ...inputFieldProps }) => {
Não sei também, teria que simular toda a Context API mt provavelmente, rsrs. Talvez seja o caso de não mockar esse componente mais e só integrar aos testes, não deve ser dificil. De qualquer forma, podemos ver isso em outro momento.

2020-09-07 22:44 UTC, calaca commented on packages/web/package.json
> +    "jest:visual": "NODE_ICU_DATA=node_modules/full-icu jest -c tests/visual/jest.config.js",
Tentei de todos os jeitos possíveis e não funciona em nenhum lugar além dos scripts mas valeu pela dica!

2020-09-07 22:58 UTC, calaca commented on packages/web/components/Form/SwitchField.js
> +						<p>{isChecked ? 'Sim' : 'Não'}</p>
@nicholasio ah sim! Perfeito! Vou fazer esse ajuste que o Mateus pediu e "finalizar" sem a integração do ConextAPI por agora só pra não segurar mais esse PR. Quando essa integração foi feita ajusto o componente Price também.

2020-09-07 23:29 UTC, nicholasio approved these changes

2020-09-08 17:16 UTC, mateus4k approved these changes
:100:

2020-09-08 17:46 UTC, lcnogueira approved these changes
Excelente trabalho, Lorena :100:

2020-09-08 17:47 UTC, merged