Área Perfil - Minhas Tecnologias Favoritas
ufersa/plataforma-sabia pull request #394
Opened 2020-09-07 14:51 UTC by luizeboli

## Summary

Resolves #295

![295](https://user-images.githubusercontent.com/13091635/92399226-54030700-f100-11ea-8ac4-58a697e4a2de.gif)
![image](https://user-images.githubusercontent.com/13091635/92399263-65e4aa00-f100-11ea-8324-4776019acce7.png)

## Relevant technical choices

* Refatorei o componente DataGrid para seja possível efetuar paginação e ordenação a partir dele. **A tela 'minhas tecnologias' não possui paginação/ordenação, se for o caso, posso fazer também, essa tela não teve o comportamento alterado**.

* Optei por não manter a responsabilidade de gerenciar a paginação e ordenação no componente DataGrid, e sim no componente da página, para que seja possível um comportamento mais customizado, se necessário. Por enquanto não parece um problema, mas futuramente podemos reavaliar, caso o código se torne muito repetitivo nas páginas para atingir esse resultado.

* Espero receber através do header `X-Sabia-Total-Pages` a quantidade total de páginas, e do header `'X-Sabia-Total` a quantidade total de itens. (A ordenação/paginação ainda não ocorre de forma funcional pela API)

## QA Steps

Quando a API estiver corrigida:

1. Clicar no menu do usuário (avatar no canto superior direito)
2. Clicar na opção **Tecnologias Favoritas**
3. Verificar se os controles de ordenação e paginação funcionam adequadamente

## Checklist

Falta apenas escrever os testes, devo terminar hoje na parte da noite.

- [X] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [X] My code passes the linting.
- [X] My code has proper inline documentation.
- [X] I have manually tested this PR.

2020-09-07 15:43 UTC, luizeboli commented
@nicholasio preciso de ajuda pra definir duas coisas:

* Quais colunas vão aparecer nessa tabela? As mesmas da tecnologia?
* Qual será a quantidade de itens por página? Hoje está 5, mas pensei em 10-15, talvez

2020-09-08 23:00 UTC, marcusmota reviewed
Deixei alguns pequenos comentário, entretanto parece-me bem o PR, nice work 👍 

**Note:** Você está colocando ASC e DESC em bastante canto, acho que seria bacana criar um enum para isso para evitar typo `e.g AsC` eu fiz algo similar aqui https://github.com/ufersa/plataforma-sabia/blob/4df8413fb48ea84d6cb8960ffe9eafdbbaf410b3/packages/web/utils/enums/technology.enums.js

2020-09-09 14:20 UTC, luizeboli commented on packages/web/components/DataGrid/Controls.js
> +	};
Dessa forma ficou realmente mais intuitivo e organizado. 

Obrigado!

2020-09-09 14:21 UTC, luizeboli commented on packages/web/pages/user/my-account/bookmarks.js
> +	};
Ficou mais limpo também

2020-09-09 14:22 UTC, luizeboli commented
Obrigado pelas sugestões @marcusmota 

Quanto ao ENUM, também costumo trabalhar assim, mas não tinha me atentado nessa situação, vou ajustar.

2020-09-11 18:43 UTC, mateus4k commented on packages/web/components/DataGrid/styles.js
> +	height: 2.2rem;
```suggestion
	${arrowIconSize}
```

2020-09-11 18:46 UTC, mateus4k commented on packages/web/pages/user/my-account/bookmarks.js
> +						{bookmarks.length > 0 ? (
```suggestion
						{!!bookmarks.length ? (
```

2020-09-11 19:27 UTC, mateus4k commented on packages/web/services/user.js
> +		{ token },
Não precisamos do token aqui. Já é incluso automaticamente lá no `apiFetch`

2020-09-11 19:29 UTC, mateus4k commented on packages/web/services/user.js
> +export const getUserBookmarks = async (userId, token, options = { embed: true }) => {
```suggestion
export const getUserBookmarks = async (userId, options = {}) => {
```

2020-09-11 19:36 UTC, mateus4k commented on packages/web/pages/user/my-account/bookmarks.js
> +		token,
Pode remover :slightly_smiling_face:

2020-09-11 19:37 UTC, mateus4k requested changes
Somente algumas pequenas modificações :slightly_smiling_face:

2020-09-11 21:48 UTC, luizeboli commented on packages/web/pages/user/my-account/bookmarks.js
> +		token,
Vou iniciar uma discussão lá no #web-package já que no SSR o token vem falsy devido o document ser undefined.

2020-09-11 21:51 UTC, luizeboli commented
Obrigado pelas sugestões @mateus4k 

Quanto ao Token no initialProps, como estávamos falando no slack, vamos precisar pensar em uma forma de pegar o token via SSR também, já que na primeira execução `document` está undefined, logo a função `getCookies` retorna false.

2020-09-12 02:15 UTC, nicholasio requested changes
Ficou muito bom 💯 !

Fiz algumas sugestões, sobretudo nos testes.

2020-09-12 02:15 UTC, nicholasio commented on packages/web/components/DataGrid/__tests__/Controls.js
> +		expect(mockHandleSortBy.mock.calls).toHaveLength(1);
```suggestion
		expect(mockHandleSortBy).toHaveBeenCalledTimes(1);
```

2020-09-12 02:15 UTC, nicholasio commented on packages/web/components/DataGrid/__tests__/Controls.js
> +		expect(mockHandleSortBy.mock.calls[0][1]).toBeUndefined();
```suggestion
		expect(mockHandleSortBy).toHaveBeenNthCalledWith(1, 'title', undefined);
```

2020-09-12 02:15 UTC, nicholasio commented on packages/web/components/DataGrid/__tests__/Controls.js
> +		expect(mockHandleSortBy.mock.calls).toHaveLength(2);
```suggestion
		expect(mockHandleSortBy).toHaveBeenCalledTimes(2);
```

2020-09-12 02:15 UTC, nicholasio commented on packages/web/components/DataGrid/__tests__/Controls.js
> +		expect(mockHandleSortBy.mock.calls[1][0]).toBe('status');
Ver as outras sugestões :)

2020-09-12 02:15 UTC, nicholasio commented on packages/web/components/DataGrid/__tests__/Controls.js
> +		expect(mockHandleSortBy.mock.calls).toHaveLength(2);
Ver as outras sugestões.

2020-09-12 02:15 UTC, nicholasio commented on packages/web/components/DataGrid/__tests__/Controls.js
> +		expect(getByLabelText('First Page')).toBeInTheDocument();
Se você usar o `screen` do react testing library você não precisa pegar o `getByLabelText`.

https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-screen

2020-09-14 13:03 UTC, luizeboli commented
Obrigado @nicholasio 

Refatorei os testes me baseando nos seus apontamentos, a questão do `screen` acho que passou batido, agora esse matcher `toHaveBeenNthCalledWith` eu não conhecia, vou dar uma lida na doc do jest pra refrescar 🎉

2020-09-14 13:37 UTC, nicholasio approved these changes

2020-09-14 14:36 UTC, mateus4k submitted a review, later dismissed
Show! :heavy_check_mark:

2020-09-17 22:06 UTC, nicholasio commented on packages/web/pages/user/my-account/bookmarks.js
> +								rowLink="/t/:id"
Tem um pequeno probleminha aqui, é pra usar o slug e não o id. Funciona com os dois mas perdemos as "pretty urls" assim.

Eu tentei passar o slug via `data` e alterar o replace pra ficar assim:

```js
href={rowLink.replace(':id', row.id).replace(':slug', row.slug)}
```
mas vi que ele adiciona automaticamente todos os campos de `data` como coluna. Precisamos de uma forma de passar dados sem necessariamente renderizar uma coluna. Alguma sugestão?

2020-09-18 14:00 UTC, luizeboli commented on packages/web/pages/user/my-account/bookmarks.js
> +								rowLink="/t/:id"
@nicholasio dá uma olhada [nesse commit](https://github.com/ufersa/plataforma-sabia/pull/394/commits/7fb05612d601194fafae17d754f532207e3907ad), incluí uma nova prop `hideItemsByKey` e a partir dela tratamos o heading e as células

2020-09-18 14:13 UTC, mateus4k commented on packages/web/components/DataGrid/DataGrid.js
> +	const internalRow = { ...row };
```suggestion
	const internalRow = row;
```

2020-09-18 19:24 UTC, nicholasio approved these changes

2020-09-18 19:25 UTC, merged