Feature/web/technology form step
ufersa/plataforma-sabia pull request #415
Opened 2020-09-10 12:45 UTC by davioliveiira

## Summary
Resolves #369

## Relevant technical choices

- Optei por utilizar o conceito de _step_ atual e implementei para refletir na url

## QA Steps

- Acessa o link de criar nova tecnologia
- Preencher informações sobre a tecnologia
- Verificar se os passos estão sendo passados na _URL_

## Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code passes the linting.
- [x] My code has proper inline documentation.
- [x] I have manually tested this PR.

2020-09-11 00:29 UTC, mateus4k commented on packages/web/components/TechnologyForm/MapAndAttachments/index.js
> +	const [previewedPdfFiles, setPreviewedPdfFiles] = useState(attachments.documents || []);
Pode usar as `defaultProps` pra isso

2020-09-11 00:32 UTC, mateus4k commented on packages/web/components/TechnologyForm/Review/index.js
> +						{technology.attachments.images && technology.attachments.images.length ? (
```suggestion
						{technology.attachments.images?.length ? (
```

2020-09-11 00:32 UTC, mateus4k commented on packages/web/components/TechnologyForm/Review/index.js
> +						technology.attachments.documents.length ? (
```suggestion
						{technology.attachments.documents?.length ? (
```

2020-09-11 00:34 UTC, mateus4k requested changes
Bom trabalho! :slightly_smiling_face::+1:

2020-09-11 20:39 UTC, davioliveiira commented on packages/web/components/TechnologyForm/MapAndAttachments/index.js
> +	const [previewedPdfFiles, setPreviewedPdfFiles] = useState(attachments.documents || []);
Alterado @mateus4k !

2020-09-11 20:39 UTC, davioliveiira commented on packages/web/components/TechnologyForm/Review/index.js
> +						{technology.attachments.images && technology.attachments.images.length ? (
Alterado @mateus4k !

2020-09-12 01:49 UTC, davioliveiira commented on packages/web/components/TechnologyForm/Review/index.js
> +						technology.attachments.documents.length ? (
Alterado @mateus4k !

2020-09-12 01:58 UTC, mateus4k approved these changes

2020-09-12 13:45 UTC, nicholasio commented
@davioliveiira Fiz algumas melhorias:

- O voltar não estava funcionando, ele não estava pegando os dados atualizados.
- Como agora temos o step na URL não precisamos do local state.
- Um dos objetivos da issue era evitar ter que fazer o `reset` e atualizar o state do form no `onSubmit`, agora todo o data fetching fica a cargo do `getInitialProps`.
- Uma outra coisa que faltou era fazer o fetch dos endpoints so nos passos necessários.

2020-09-14 12:24 UTC, luizeboli reviewed
Bom trampo, parabéns 🎉

Fiz uma sugestão no teste, pra deixar mais claro..

~~Percebi que existem 3 linhas onde o linter pede formatação no arquivo `pages/technology/[id]/edit`, 2 delas já existiam e 1 surgiu no seu PR, seria interessante corrigir todos, já que está atuando nesse arquivo 💯~~ `desconsiderar`

2020-09-14 12:24 UTC, luizeboli commented on packages/web/services/__tests__/technology.js
> +	test('it returns empty if request fails', async () => {
```suggestion
	test('it returns an empty array if request fails', async () => {
```

Acredito que assim o teste fica mais fácil de ler ao bater o olho, deixando explícito o que é`empty`

2020-09-14 12:24 UTC, luizeboli commented on packages/web/pages/technology/[id]/edit.js
> +			technology.attachments = await getAttachments(query.id, { normalize: true });
Podes mandar um fix do ESLint nessa linha?

2020-09-14 12:24 UTC, luizeboli commented on packages/web/services/__tests__/technology.js
> +	test('it returns empty if request fails', async () => {
```suggestion
	test('it returns an empty array if request fails', async () => {
```

Acredito que assim a leitura do teste fica mais fácil e intuitiva ao bater o olho, deixando explícito o que é `empty`

2020-09-14 12:24 UTC, luizeboli commented on packages/web/pages/technology/[id]/edit.js
> +			technology.attachments = await getAttachments(query.id, { normalize: true });
Podes mandar um fix do ESLint aqui?

2020-09-15 12:01 UTC, davioliveiira commented on packages/web/services/__tests__/technology.js
> +	test('it returns empty if request fails', async () => {
Feito

2020-09-15 12:14 UTC, mateus4k commented on packages/web/pages/technology/[id]/edit.js
>  						window.scrollTo({ top: 0 });
Esse `await` existia para que o scroll só ocorresse na nova página. Sem isso, o scroll acontecia antes do redirecionamento finalizar e dava uma impressão estranha. Continua funcionando da mesma forma?

2020-09-15 12:18 UTC, nicholasio commented on packages/web/pages/technology/[id]/edit.js
>  						window.scrollTo({ top: 0 });
mas `router.push` retorna uma promise?

2020-09-15 12:38 UTC, lcnogueira commented on packages/web/pages/technology/[id]/edit.js
>  						window.scrollTo({ top: 0 });
Acho que retorna sim. Teve algum local (não se lembro se nesse específico), que eu adicionei um `await` porque tinha esse comportamento estranho que Mateus falou.

2020-09-15 12:48 UTC, luizeboli commented on packages/web/pages/technology/[id]/edit.js
>  						window.scrollTo({ top: 0 });
Retorna uma promise do tipo bool

2020-09-17 21:54 UTC, nicholasio commented on packages/web/pages/technology/[id]/edit.js
>  						window.scrollTo({ top: 0 });
re-adicionado.

2020-09-17 21:54 UTC, merged