Feature/web/privacy policy
ufersa/plataforma-sabia pull request #454
Opened 2020-09-26 20:58 UTC by calaca

## Summary

Resolves #434 

Depends on #452 (this branch is based on #452 because they share the same styles file)

## Relevant technical choices

- Same as #452 

## QA Steps

- Same as #452 

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2020-09-27 04:09 UTC, nicholasio requested changes

2020-09-27 04:09 UTC, nicholasio commented on packages/web/components/TermsAndPolicies/styles.js
> +		ul {
Para diminuir os níveis aqui sugiro reescrever esses seletores.

e.g: 

```css
ul li {
  //
  ol, ul {
    //
    li {
    }
    li ol li, li ul li {
    //
    }
  }
  
}
```

2020-09-27 04:09 UTC, nicholasio commented on packages/web/pages/terms-of-use.js
> +		<>
Esse fragment aqui é desnecessário

2020-10-01 00:42 UTC, calaca commented
Fechando para criar a branch novamente a partir da master a fim de resolver o problema na cobertura de testes.

2020-10-01 00:42 UTC, closed without merging