Correção: Upload - corrigir erro quando arquivo já existir
ufersa/plataforma-sabia pull request #462
Opened 2020-10-02 16:19 UTC by NaylsonFerreira

## Summary

Resolves #461 

## Relevant technical choices
Seguindo as sugestões em #445 e no Slack
* Removida a variável de ambiente `UPLOADS_PATH`
* Adicionado o arquivo de configuração em `config/upload.js`
* Refatorado o Validator `Upload.js` para importa a configuração de `config/upload.js`
* Adicionado a função recursiva `checkFileExist` que trata o nome do novo arquivo caso o diretório não esteja sincronizado com o banco.

## QA Steps

## Checklist

- [X] My code is tested and passes existing unit tests.
- [X] My code has an appropriate set of unit tests which all pass.
- [X] My code passes the linting.
- [X] My code has proper inline documentation.
- [X] I have manually tested this PR.

2020-10-02 21:40 UTC, alexandreadames requested changes
@NaylsonFerreira ficou muito bom. Pra fechar com chave de ouro basta você criar um teste simulando a criação de um filename único caso ele exista na pasta, porém não existindo no banco. Atestando que o método recursivo que você fez está mesmo trabalhando da forma como deveria.

2020-10-02 21:42 UTC, alexandreadames commented
> @NaylsonFerreira ficou muito bom. Pra fechar com chave de ouro basta você criar um teste simulando a criação de um filename único caso ele exista na pasta, porém não existindo no banco. Atestando que o método recursivo que você fez está mesmo trabalhando da forma como deveria.

Acabei de ver que você já fez isso! kk

2020-10-02 21:43 UTC, alexandreadames approved these changes
Show!

2020-10-03 14:17 UTC, alexandreadames commented on packages/api/app/Models/Upload.js
> +const fs = Helpers.promisify(require('fs'));
@nicholasio, nas primeiras versões do upload eu usava funções assíncronas do fs, por isso eu usava o `promisify`. Depois eu descobri que o próprio pacote disponibilizava funções nativamente síncronas como em: 
```javascript
fs.unlinkSync(Helpers.publicPath(`${uploadPath}/${file.fileName}`));
```
Eu dei uma olhada no código e vi que tem lugares que ainda usam promises. @NaylsonFerreira por favor, substitua todos os lugares onde usa a sintaxe:
```javascript
await fs.unlink(Helpers.publicPath(`${uploadPath}/${upload.filename}`));
```
Pelas versões sincronas e retire o promisify

2020-10-03 17:37 UTC, NaylsonFerreira commented on packages/api/app/Models/Upload.js
> +const fs = Helpers.promisify(require('fs'));
Certo!

2020-10-03 18:43 UTC, alexandreadames approved these changes
Isso mesmo @NaylsonFerreira. Parabéns!

2020-10-03 19:27 UTC, nicholasio approved these changes
@alexandreadames @NaylsonFerreira com relação ao promisify, na verdade é melhor usar ele mesmo. Pra evitar prolongar essa PR e como estamos usamos métodos sincronos em outros locais da API, criei uma nova issue para alterar essa parte: https://github.com/ufersa/plataforma-sabia/issues/468

2020-10-03 19:30 UTC, merged