hotfix/web/about-technology
ufersa/plataforma-sabia pull request #467
Opened 2020-10-03 14:50 UTC by calaca

## Summary

Resolves #457 

- [X]  All select options are now ordered alphabetically

![image](https://user-images.githubusercontent.com/10481028/94993301-5b35fd00-0566-11eb-8b72-c33f34bbe932.png)

- [X] Change order between fields "Tem patente?" and "Proteção Intelectual da tecnologia". Replace "Tem patente?" label by "Tem registro de patente?"

![image](https://user-images.githubusercontent.com/10481028/94993546-35a9f300-0568-11eb-82be-b6096379242a.png)

- [ ] Hide "Tem registro de patente?" field by default and show it only when "Proteção Intelectual da tecnologia" select has "Propriedade Intelectual" option selected. (Waiting discussion about this item)

- [X] Create required field indicator and information indicator

![image](https://user-images.githubusercontent.com/10481028/94993321-7c96e900-0566-11eb-8a0c-5a3131ea683d.png)

- [X] Add hint to select fields that have creatable options enabled

![image](https://user-images.githubusercontent.com/10481028/94993313-6ab54600-0566-11eb-8944-c7430a6566b7.png)

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2020-10-04 18:31 UTC, calaca commented
@nichollasrennah @nicholasio @alexandreadames pessoal, ajustei o input da proteção intelectual, mudando ele pra um switch e só apresentando o switch de patente caso o primeiro esteja marcado com "sim":

![captured](https://user-images.githubusercontent.com/10481028/95023921-2c974f80-0656-11eb-9ae2-8635e2ea37fa.gif)

Removi esse switch de proteção intelectual dos terms, pois não faz mais sentido ele estar lá por não ser mais um termo. Deixei ele no corpo dos dados de formulário como "intellectual_property" mesmo. O formulário não quebra na criação de uma nova tecnologia mas é preciso ajustar a API e o banco para se adequar ao novo formato desse dado. Bem como é preciso atualizar o seed. @alexandreadames pode dar uma ajuda nesses pontos da API?

2020-10-10 20:02 UTC, lcnogueira commented
@calaca , tô só me atualizando aqui: em que situação está esse PR?

2020-10-11 18:50 UTC, calaca commented
> @calaca , tô só me atualizando aqui: em que situação está esse PR?

Estou ajustando documentação e testes na API. Assim que estiver ok tiro do draft e mudo os revisores.

2020-10-11 21:25 UTC, calaca commented
Tive que alterar o comando do Cypress que selecionava o primeiro elemento do select para aceitar uma posição _N_ nas opções. O motivo disso é que a categoria "Adução" não possui sub-categorias e com isso quebrava dois testes que checavam que as opções da sub-categoria sao carregadas logo após selecionar uma categoria.

A utilização fica assim: `cy.select('id', { exactMatch: true, position: 2 });`
Sendo que _position_ é opcional e o padrão é a primeira posição.

PS: os testes de cobertura que quebraram não tem a ver com alterações que fiz.

2020-10-13 01:41 UTC, lcnogueira commented on packages/web/components/Form/Required/Indicator.js
> +	return <IndicatorStyled aria-label="Indicador visual de campo obrigatório">*</IndicatorStyled>;
👌

2020-10-13 01:48 UTC, lcnogueira submitted a review, later dismissed
Muito bom trabalho, @calaca ! 💯 

Só resolve os conflitos e se realizar alguma mudança substancial, pode me marcar novamente para revisão. Se não, por mim pode fazer o merge 👍

2020-10-13 01:48 UTC, lcnogueira commented on packages/web/components/Form/SelectField.js
> +	margin: 0 0 1rem 0;
Mais simples colocar só o `margin-left, não? 😛

2020-10-13 16:58 UTC, luizeboli requested changes
Excelente! Good job 💯 

Testei os pontos da issue e todos estão de acordo ✔ 

Algumas observações: 

@calaca Acho muito válida a adição desse `RequiredIndicator`, mas, da forma que alguns fields são dispostos em tela hoje, sem label, acabou ficando estranha a visualização apenas com o asterisco. O que acha? E se colocássemos o asterisco junto do placeholder quando o campo fosse required e não existisse label? 

Outro problema em decorrência disso, foi que tornamos menos intuitivo para o usuário deduzir se o asterisco é do input de cima ou de baixo, usando como exemplo esse form de login, já que não existe muita margem entre os inputs 

![image](https://user-images.githubusercontent.com/13091635/95890394-2130dc00-0d5a-11eb-9f72-194bf99ab1ef.png)

-----

Um outro ponto de sugestão:

Eu estava lendo sobre UX de forms, e colocar a indicação de campo obrigatório no começo do form ao invés do final, facilita a identificação do usuário sobre os campos requeridos, já que como começamos a leitura de cima pra baixo, e esquerda-direita, o usuário já chega no input sabendo que o asterisco é representação de obrigatoriedade.

![image](https://user-images.githubusercontent.com/13091635/95891705-d57f3200-0d5b-11eb-82b0-b3cd49981c35.png)

---

O último 😄 

Podemos usar pascal case na tecla: `Enter`

![image](https://user-images.githubusercontent.com/13091635/95892307-ba60f200-0d5c-11eb-81ab-8ebf9973c155.png)

2020-10-13 22:30 UTC, calaca commented on packages/web/components/Form/SelectField.js
> +	margin: 0 0 1rem 0;
@lcnogueira  Sim! Só deixei assim pq tb é como tá nos estilos dos erros. Peguei tudo igual lá, menos a cor haha

2020-10-13 22:33 UTC, calaca commented
> Excelente! Good job 
> 
> Testei os pontos da issue e todos estão de acordo 
> 
> Algumas observações:
> 
> @calaca Acho muito válida a adição desse `RequiredIndicator`, mas, da forma que alguns fields são dispostos em tela hoje, sem label, acabou ficando estranha a visualização apenas com o asterisco. O que acha? E se colocássemos o asterisco junto do placeholder quando o campo fosse required e não existisse label?
> 
> Outro problema em decorrência disso, foi que tornamos menos intuitivo para o usuário deduzir se o asterisco é do input de cima ou de baixo, usando como exemplo esse form de login, já que não existe muita margem entre os inputs
> 
> ![image](https://user-images.githubusercontent.com/13091635/95890394-2130dc00-0d5a-11eb-9f72-194bf99ab1ef.png)
> 
> Um outro ponto de sugestão:
> 
> Eu estava lendo sobre UX de forms, e colocar a indicação de campo obrigatório no começo do form ao invés do final, facilita a identificação do usuário sobre os campos requeridos, já que como começamos a leitura de cima pra baixo, e esquerda-direita, o usuário já chega no input sabendo que o asterisco é representação de obrigatoriedade.
> 
> ![image](https://user-images.githubusercontent.com/13091635/95891705-d57f3200-0d5b-11eb-82b0-b3cd49981c35.png)
> 
> O último 
> 
> Podemos usar pascal case na tecla: `Enter`
> 
> ![image](https://user-images.githubusercontent.com/13091635/95892307-ba60f200-0d5c-11eb-81ab-8ebf9973c155.png)

@luizeboli pontos super válidos! Obrigada!

Vou aplicar os ajustes que vc sugeriu! Só acho que seria interessante manter o `RequiredIndicator` como está para labels pois acho mais fácil do usuário identificar que é um campo obrigatório por ser mais visível e ser algo que já estamos acostumados a ver. No caso de usarmos campos sem labels, acho pertinente usarmos essa sugestão que vc deu de sempre usar o "*" no placeholder. Que tal?

2020-10-13 23:44 UTC, calaca commented
@luizeboli seguem os ajustes pedidos:

Indicador de obrigatório quando não tem label:
![image](https://user-images.githubusercontent.com/10481028/95925781-12b1e700-0d91-11eb-9d7d-7ea0b8176744.png)
***
Indicador de obrigatório quando existe label e local da informação de obrigatoriedade:
![image](https://user-images.githubusercontent.com/10481028/95925938-6c1a1600-0d91-11eb-8a94-99a986c0048e.png)
***
Texto de dica do select:
![image](https://user-images.githubusercontent.com/10481028/95925917-645a7180-0d91-11eb-972b-cb3df4dee1f2.png)
***
@lcnogueira Também ajustei o input com máscara, que foi reescrito e entrou pra cá com o merge que fiz da master:
![image](https://user-images.githubusercontent.com/10481028/95926399-96b89e80-0d92-11eb-8da4-374761c9ec5c.png)
_sem label_
![image](https://user-images.githubusercontent.com/10481028/95926410-9e784300-0d92-11eb-8caa-a5471310efb3.png)
_com label_

2020-10-14 01:09 UTC, lcnogueira approved these changes
Excelente, trabalho Lorena 👍 💯

2020-10-14 01:36 UTC, mateus4k commented on packages/web/styles/theme.js
> +		lightGray5: 'hsl(0, 0%, 90%)',
Não dá pra usar o 4 aqui? É tão pequena a diferença :sweat_smile:

2020-10-14 02:30 UTC, luizeboli commented
Excelente @calaca, concordo quando se refere ao asterisco nas labels,  é super válido e aprovado 🎉

2020-10-14 02:32 UTC, luizeboli approved these changes

2020-10-14 23:23 UTC, calaca commented on packages/web/styles/theme.js
> +		lightGray5: 'hsl(0, 0%, 90%)',
@mateus4k eu tentei com ele mas não gostei do contraste de tons de cinza. Tentei com todos os outros mas achei que esse novo que criei ficou melhor mesmo.

2020-10-14 23:28 UTC, merged