Hotfix/register responsive
ufersa/plataforma-sabia pull request #475
Opened 2020-10-07 19:04 UTC by luizeboli

## Summary

Resolves #472

![RegisterModal](https://user-images.githubusercontent.com/13091635/95375896-ab8ac300-08b6-11eb-9021-5178ce70c9c3.gif)

## Relevant technical choices

**Depende do PR #470 pois utilizo a mesma estrutura de custom modal**

## QA Steps

1. Abrir o modal de cadastro de usuários
2. Alterar a largura da tela para diferentes valores e verificar a responsividade do modal.

## Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code passes the linting.
- [x] My code has proper inline documentation.
- [x] I have manually tested this PR.

2020-10-07 19:05 UTC, luizeboli commented
Só reforçando, precisamos aguardar o merge da PR #470 pois aqui utilizo a mesma estrutura de custom modal.

2020-10-07 23:11 UTC, mateus4k commented on packages/web/public/static/locales/pt/common.json
> +  "registerTitle": "<span>Você está prestes <br /> a descobrir um<br /> mundo de oportunidades</span>",
Show de bola! :100:
Só não entendo pq colocamos spans nos locales :thinking:

2020-10-07 23:11 UTC, mateus4k approved these changes

2020-10-07 23:12 UTC, mateus4k commented
Ainda está pendente de merge da outra PR mas já aprovo o que foi feito agora desde já :sweat_smile:

2020-10-08 01:50 UTC, luizeboli commented on packages/web/public/static/locales/pt/common.json
> +  "registerTitle": "<span>Você está prestes <br /> a descobrir um<br /> mundo de oportunidades</span>",
Só pra conseguir usar o `word-break` 😄

2020-10-12 23:54 UTC, calaca submitted a review, later dismissed
Aprovado! Bom trabalho, @luizeboli !

2020-10-13 02:24 UTC, lcnogueira requested changes
Muito bom, @luizeboli !

Eu acho que merece só mais um pequeno ajuste e telas small, pra deixar o botão sozinho ocupando a largura e os 2 textos na linha de baixo, porque senão fica o texto e o botão bem "apertado". Tipo assim:

![39F7210B-E3F9-4A2F-8019-24B2C23E784B_4_5005_c](https://user-images.githubusercontent.com/12154623/95808099-19cdec00-0ce2-11eb-9f0c-10ba196bb167.jpeg)

2020-10-13 22:32 UTC, lcnogueira approved these changes
LGTM 👍 💯

2020-10-13 22:36 UTC, calaca approved these changes
Confirmado! :100:

2020-10-14 01:10 UTC, mateus4k commented on packages/web/components/Modal/RegisterModal/index.js
> +};
Achei estranho essa prop ser obrigatória e também não vi uma implementação. Onde vi o uso desse modal (nessa PR) as props eram undefined :sweat_smile:

2020-10-14 01:11 UTC, mateus4k commented on packages/web/components/Modal/LoginModal/index.js
> +				<Button onClick={() => openModal('register', undefined, { customModal: true })}>
Ver comentário acima :point_up_2:

2020-10-14 23:58 UTC, merged