added Disclaimer on user registration
ufersa/plataforma-sabia pull request #485
Opened 2020-10-12 21:01 UTC by NaylsonFerreira

## Summary

Resolves #473 

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2020-11-01 14:28 UTC, NaylsonFerreira commented on packages/api/test/utils/General.js
> +const createUser = async (data) => {
@mateus4k  isso aqui é igual ao seu makeSut.

2020-11-01 14:29 UTC, NaylsonFerreira commented on packages/api/test/utils/General.js
> +const createUser = async (data) => {
preciso criar um usuário e fazer ele aceitar os termos de uso

2020-11-03 23:24 UTC, mateus4k commented on packages/api/test/utils/General.js
> +const createUser = async (data) => {
Show! Estava refatorando aquele exemplo que mostrei pra ficar mais reutilizável também 💯

2020-11-11 11:55 UTC, luizeboli commented
@NaylsonFerreira 

Se entendi certo, precisamos mandar o ID dos termos no ato do cadastro, certo?

A dúvida que surgiu é: em algum momento teremos acesso a esses termos, pra pegar os IDs? Pois eles podem ser diferentes entre os ambientes. Exemplo:

Se no front mandarmos `[1,2,3,4]` pode ser que em algum momento os termos tenham IDs `[3,54,6,31]`

2020-11-11 12:03 UTC, luizeboli commented on packages/api/database/seeds/10_DisclaimerSeeder.js
> +					'Concordo com o processamento dos meus dados pessoais para fins de fornecimento dos serviços da Plataforma Sabiá. Veja mais na Política de Privacidade. ',
Todos esses "Veja mais..." precisariam ser links para os respectivos termos, dessa forma acho que não conseguiremos fazer.

Vejo como opção remover esses trechos de "Veja mais..." e deixar pra mapear isso no front, pra conseguir fazer a âncora. Talvez só seja necessário adicionar mais uma propriedade, além do `type`, ou juntar, pra indicar qual termo é, e não se basear apenas na description, exemplo:

`type: 'termsOfUseRegister',
scope: 'privacy_policy',
`

2020-11-13 10:44 UTC, lcnogueira requested changes
Naylson, fiz uma revisão por cima...deixei só uns comentários simples. Bom trabalho 🤝 👍

2020-11-13 10:44 UTC, lcnogueira commented on packages/api/app/Middleware/DisclaimerMiddleware.js
> +				.then((result) =>
Esse trecho é assim mesmo, com `await` e `.then`? Acho que aqui poderia ser um ou outro:
```
const disclaimers = await user.disclaimers((build) => build.select('id')}).fetch();
const userDisclaimers = disclaimers.toJSON().map(row => row.id);
```

A não ser que tenha algo que não tô percebendo, pode ser assim...

2020-11-13 10:44 UTC, lcnogueira commented on packages/api/app/Models/User.js
> +			);
Aqui também o mesmo comentário ali de cima: estamos usando o `await` e o `.then`no mesmo local, quando na verdade, o await é só uma sintaxe diferente pra fazer a mesma coisa.

2020-11-13 10:44 UTC, lcnogueira commented on packages/api/app/Models/User.js
> +		const arrayChecked = await Disclaimer.query()
Ver comentário acima...

2020-11-14 14:45 UTC, NaylsonFerreira commented on packages/api/database/seeds/10_DisclaimerSeeder.js
> +					'Concordo com o processamento dos meus dados pessoais para fins de fornecimento dos serviços da Plataforma Sabiá. Veja mais na Política de Privacidade. ',
É uma boa sugestão, Se @nichollasrennah  tiver essa lista com os 'scope'

2020-11-15 20:04 UTC, mateus4k commented on packages/api/test/functional/auth.spec.js
>  	const t = await u.generateToken('confirm-ac');
What's `u` and `t`? 🤔

2020-11-15 20:04 UTC, mateus4k commented on packages/api/app/Models/Disclaimer.js
> +	}
É melhor que isso daqui seja um scope e o `fetch` seja feito fora do model

2020-11-15 20:04 UTC, mateus4k commented on packages/api/app/Middleware/DisclaimerMiddleware.js
> +		const disclaimersMandatotyIds = disclaimersMandatoty.toJSON().map((row) => {
```suggestion
		const disclaimersMandatory = await Disclaimer.disclaimersMandatotyType(properties);
		const disclaimersMandatoryIds = disclaimersMandatoty.toJSON().map((row) => {
```

2020-11-16 16:33 UTC, NaylsonFerreira commented on packages/api/app/Controllers/Http/DisclaimerController.js
> +		return disclaimers.withParams(request);
Tem razão, ficou muito melhor e no padrão dos outros Contollers.

2020-11-16 16:49 UTC, NaylsonFerreira commented on packages/api/app/Controllers/Http/DisclaimerController.js
> +		return Disclaimer.find(id);
Podemos retornar apenas o status 204 daqui em diante. O que acha @alexandreadames ?
Mas atualmente todos os controllers respondem com o objeto modificado acho que usamos isso para verificar nos testes se o update realmente funcionou.

2020-11-16 17:02 UTC, NaylsonFerreira commented on packages/api/app/Controllers/Http/DisclaimerController.js
> +	async destroyMany({ request, response }) {
Já estamos usamos isso no admin.

2020-11-16 17:09 UTC, NaylsonFerreira commented on packages/api/app/Middleware/DisclaimerMiddleware.js
> +		const disclaimersMandatotyIds = disclaimersMandatoty.toJSON().map((row) => {
Estava escrito errado em 10 lugares kk

2020-11-16 17:22 UTC, NaylsonFerreira commented on packages/api/app/Models/Disclaimer.js
> +	}
Removi esse metodo 👍

2020-11-17 02:40 UTC, mateus4k approved these changes
Show de bola! Conflitará um pouco com a minha PR na parte do Sut de usuário mas faz parte kkkkkk 💯

2020-11-17 02:40 UTC, mateus4k commented on packages/api/app/Middleware/DisclaimerMiddleware.js
> +			.fetch();
```suggestion
		const disclaimersMandatory = await Disclaimer.query()
			.select('id')
			.where({
				required: true,
				type: properties,
			})
			.fetch();
```

2020-11-17 02:40 UTC, mateus4k commented on packages/api/app/Middleware/DisclaimerMiddleware.js
> +				const temp = container.filter((i) => elements.includes(i));
```suggestion
				const temp = container.filter((item) => elements.includes(item));
```

2020-11-17 02:40 UTC, mateus4k commented on packages/api/app/Middleware/DisclaimerMiddleware.js
> +				};
Isso aqui deveria estar lá no `app/Utils/errors.js`, não? 🤔

2020-11-17 12:58 UTC, NaylsonFerreira commented on packages/api/app/Middleware/DisclaimerMiddleware.js
> +				};
É que a função error não espera esse argumento `payload` 
https://github.com/ufersa/plataforma-sabia/blob/master/packages/api/app/Utils/errors.js#L20

O padrão seria assim 
`return response.status(401).send(errorPayload(errors.TERMSOFUSE, request.antl('error.termsOfUse')));`
 mas quero enviar os disclaimers necessários para aquela rota no error, para evitar outra requisição do usuário.

2020-11-17 13:00 UTC, NaylsonFerreira commented on packages/api/app/Middleware/DisclaimerMiddleware.js
> +			.fetch();
Aqui vou usar o resultado dessa query como payload no caso de error.

2020-11-17 15:17 UTC, mateus4k commented
Dá um merge com a master pra atualizar o CI e resolver o conflito no teste de technology

2020-11-18 02:54 UTC, mateus4k commented
Pode migrar o teu sut de user para o método que criei em `test/utils/Suts`?

2020-11-19 20:56 UTC, mateus4k submitted a review, later dismissed

2020-11-19 22:42 UTC, alexandreadames requested changes
Show de Bola! Apenas umas pequenas sugestões. 🥇

2020-11-19 22:42 UTC, alexandreadames commented on packages/api/start/routes/disclaimers.js
> + *    }
```suggestion

```
Essa rota não é protegida

2020-11-19 22:42 UTC, alexandreadames commented on packages/api/start/routes/disclaimers.js
> + *	/disclaimers/1
```suggestion
 * @apiParamExample  {json} Request sample:
 *	/disclaimers
```
Essa rota não é protegida

2020-11-19 22:42 UTC, alexandreadames commented on packages/api/start/routes/disclaimers.js
> + */
Em geral esse erro não se aplica a rotas do tipo `index`. É isso mesmo?

2020-11-19 22:42 UTC, alexandreadames commented on packages/api/start/routes/disclaimers.js
> +
```suggestion
```
Esse erro se aplica quando o middleware `Permission` é chamado.

2020-11-19 22:42 UTC, alexandreadames commented on packages/api/test/functional/auth.spec.js
> +const disclaimers = Array.from(Array(30).keys());
Aqui é melhor pegar todos os ids dos disclaimers que existem, fazendo assim pode-se futuramente quebrar os testes, caso existam mais de 30 disclaimers no seeder.

2020-11-19 22:42 UTC, alexandreadames commented on packages/api/test/functional/disclaimers.spec.js
> +		.delete(`/disclaimers/${disclaimerSalved.id}/`)
```suggestion
		.delete(`/disclaimers/${disclaimerSalved.id}`)
```

2020-11-19 22:42 UTC, alexandreadames commented on packages/api/test/functional/disclaimers.spec.js
> +});
Aqui nesse teste seria interessante mandar o array de `disclaimers` mas incompleto, para mostrar que ele só aceitou parte dos termos.

2020-11-19 22:53 UTC, mateus4k commented on packages/api/test/functional/auth.spec.js
> +const disclaimers = Array.from(Array(30).keys());
Coitado do usuário que vai ter que acessar tudo isso 😆

2020-11-19 22:54 UTC, mateus4k commented
Excelente revisão, @alexandreadames 👏

2020-11-20 00:14 UTC, NaylsonFerreira commented on packages/api/app/Validators/User.js
> +			'disclaimers.*': 'number',
Deixei comentado porque colocar isso agora vai quebrar o front.
Na integração tem que fazer um get e depois manda o post em /auth/register

2020-11-20 00:16 UTC, NaylsonFerreira commented on packages/api/test/functional/auth.spec.js
> +const disclaimers = Array.from(Array(30).keys());
Eh "temporário", vamos fazer a integração em outra issue.

2020-11-20 00:16 UTC, NaylsonFerreira commented on packages/api/test/functional/disclaimers.spec.js
> +});
Feito!

2020-11-20 00:29 UTC, mateus4k commented on packages/api/app/Validators/User.js
> +			'disclaimers.*': 'number',
Pode adicionar na issue referente a isso a observação para descomentar essa linha?

2020-11-20 00:35 UTC, alexandreadames commented on packages/api/test/functional/auth.spec.js
> +const disclaimers = Array.from(Array(30).keys());
Boa

2020-11-20 00:35 UTC, alexandreadames submitted a review, later dismissed
Excelente trabalho Dr. @NaylsonFerreira

2020-11-20 00:39 UTC, NaylsonFerreira commented on packages/api/app/Validators/User.js
> +			'disclaimers.*': 'number',
Não encontrei a issue para isso. Acho que precisa ser criada ou posso fazer isso na issue #575

2020-11-20 00:39 UTC, mateus4k requested changes
Algumas pequenas mudancas, somente xD

2020-11-20 00:39 UTC, mateus4k commented on packages/api/test/functional/disclaimers.spec.js
> +test('POST /disclaimers', async ({ client }) => {
```suggestion
test('POST /disclaimers works successfully.', async ({ client }) => {
```

2020-11-20 00:39 UTC, mateus4k commented on packages/api/test/functional/disclaimers.spec.js
> +test('PUT /disclaimers', async ({ client }) => {
```suggestion
test('PUT /disclaimers works successfully', async ({ client }) => {
```

2020-11-20 00:39 UTC, mateus4k commented on packages/api/test/functional/disclaimers.spec.js
> +test('DELETE /disclaimers', async ({ client }) => {
```suggestion
test('DELETE /disclaimers works successfully', async ({ client }) => {
```

2020-11-20 00:39 UTC, mateus4k commented on packages/api/test/functional/disclaimers.spec.js
> +test('/disclaimers make sure the user role is admin', async ({ client }) => {
```suggestion
test('POST /disclaimers returns an error when the user is not an administrator', async ({ client }) => {
```

2020-11-20 00:39 UTC, mateus4k commented on packages/api/test/functional/disclaimers.spec.js
> +		.header('Accept', 'application/json')
Não precisamos declarar os headers neste teste

2020-11-20 00:39 UTC, mateus4k commented on packages/api/test/functional/disclaimers.spec.js
> +	});
Transformar nua variável será útil para diminuir a verbosidade dos três casos de uso neste teste
```suggestion
	const unauthorizedAccessError = {
		error: {
			error_code: 'UNAUTHORIZED_ACCESS',
			message: 'You do not have permission to access this resource',
		},
	};
	
	response.assertJSONSubset(unauthorizedAccessError);
```

2020-11-20 00:39 UTC, mateus4k commented on packages/api/test/functional/disclaimers.spec.js
> +test('POST /auth/register the endpoint fails when the user does not accept all the terms of use', async ({
```suggestion
test('POST /auth/register returns an error when the user does not accept all terms of use', async ({
```

2020-11-20 00:46 UTC, NaylsonFerreira commented on packages/api/test/functional/disclaimers.spec.js
> +		.header('Accept', 'application/json')
```suggestion

```

2020-11-20 00:47 UTC, mateus4k commented on packages/api/test/functional/disclaimers.spec.js
> +		.header('Accept', 'application/json')
Também sugiro essa mudança 😂

2020-11-20 01:12 UTC, alexandreadames approved these changes
👍

2020-11-20 01:12 UTC, NaylsonFerreira commented on packages/api/test/functional/disclaimers.spec.js
> +		.header('Accept', 'application/json')
😂

2020-11-20 01:12 UTC, mateus4k submitted a review, later dismissed
👍

2020-11-20 12:07 UTC, mateus4k approved these changes

2020-11-20 13:01 UTC, lcnogueira approved these changes
LGTM 👍

2020-11-20 13:31 UTC, merged