Refactored seeds
ufersa/plataforma-sabia pull request #492
Opened 2020-10-13 20:15 UTC by NaylsonFerreira

## Summary

Rodar os testes **funcionais**  mais rápido localmente. 

## Relevant technical choices

## QA Steps

`npm run test`
## Checklist

- [X] My code is tested and passes existing unit tests.
- [X] My code has an appropriate set of unit tests which all pass.
- [X] My code passes the linting.
- [X] My code has proper inline documentation.
- [X] I have manually tested this PR.

2020-10-14 01:51 UTC, mateus4k commented on packages/api/database/seeds/4_TechnologySeeder.js
> +		};
Será que dá pra mover isso aqui lá pros utils de forma mais genérica pra reutilizarmos nos outros seeders?

2020-10-14 19:11 UTC, alexandreadames approved these changes
Muito bom!

2020-10-19 21:26 UTC, alexandreadames requested changes
Com essa pequenas alterações tá muito bom.

2020-10-19 21:26 UTC, alexandreadames commented on packages/api/database/seeds/4_TechnologySeeder.js
> +				const subCategoryTerm = getRandom(categoryTerms);
@NaylsonFerreira eu percebi um pequeno erro aqui. No caso da taxonomia de categoria você precisa primeiro sortear uma categoria pai e depois carregar as categorias filhas e sortear uma dentre elas. Favor faça essa alteração e teste.

```suggestion
				const subCategoryTerms = await Taxonomy.getTaxonomyTerms('CATEGORY', categoryTerm.id);
				const subCategoryTerm = getRandom(subCategoryTerms);
```

2020-10-19 21:26 UTC, alexandreadames commented on packages/api/database/seeds/4_TechnologySeeder.js
> +				/** Create a CLASSIFICATION in Technology */
Trocar os comentários, para algo do tipo "Sorteia uma classificação"

2020-10-20 23:02 UTC, alexandreadames approved these changes
Muito bom!

2020-10-22 00:40 UTC, mateus4k approved these changes
LGTM 👍

2020-10-22 01:33 UTC, merged