Detalhamento de Tecnologia - Estágios de Desenvolvimento
ufersa/plataforma-sabia pull request #496
Opened 2020-10-15 14:03 UTC by luizeboli

## Summary

Resolves #213

![image](https://user-images.githubusercontent.com/13091635/96140142-fec3cd80-0ed5-11eb-83a3-381e2ec7a33d.png)

## Relevant technical choices

Essa section só aparece caso o estágio de desenvolvimento da tecnologia for maior ou igual a 7

## QA Steps

1. Acessar a página de alguma tecnologia que esteja em estágio de desenvolvimento maior ou igual a 7

## Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code passes the linting.
- [x] My code has proper inline documentation.
- [x] I have manually tested this PR.

2020-10-15 16:31 UTC, mateus4k commented on packages/web/__tests__/pages/t/__snapshots__/index.js.snap
> +
:thinking:

2020-10-15 16:35 UTC, luizeboli commented on packages/web/__tests__/pages/t/__snapshots__/index.js.snap
> +
Pra mim isso ai é algum bug do snapshot :/

2020-10-15 16:37 UTC, luizeboli commented on packages/web/__tests__/pages/t/__snapshots__/index.js.snap
> +
Existe um media query no componente `ReadinessLevel` pra tratar o size da imagem:

```Javascript
		@media screen and (max-width: ${screens.medium}px) {
			> img {
				max-width: 100%;
			}
		}
```

2020-10-15 16:40 UTC, mateus4k commented on packages/web/components/Technology/Details/ReadinessLevel/index.js
> +	const { slug } = normalizeTrl(terms);
Acho que assim fica mais lindo :sweat_smile: 
```suggestion
	const { technology } = useTechnology();
	const { slug } = normalizeTrl(technology.terms);
```

2020-10-15 16:40 UTC, mateus4k requested changes
Bacana! Só uma sugestão mesmo

2020-10-15 16:41 UTC, luizeboli commented on packages/web/components/Technology/Details/ReadinessLevel/index.js
> +	const { slug } = normalizeTrl(terms);
O default assign era pra garantir que se algo vier `undefined` não vá quebrar as interações. O que acha?

2020-10-15 22:45 UTC, mateus4k commented on packages/web/__tests__/pages/t/__snapshots__/index.js.snap
> +
Aconteceu comigo esses dias também :/

2020-10-15 22:47 UTC, mateus4k commented on packages/web/components/Technology/Details/ReadinessLevel/index.js
> +	const { slug } = normalizeTrl(terms);
Acho que então seria bacana um optional chaining e lá na função de normalize ter a checassem se existe algo ou não.
```suggestion
	const { technology } = useTechnology();
	const { slug } = normalizeTrl(technology?.terms);
```

2020-10-16 00:45 UTC, lcnogueira approved these changes
LGTM 👍

2020-10-16 13:15 UTC, mateus4k approved these changes

2020-10-16 13:53 UTC, merged