Atualizando foto principal "Hero"
ufersa/plataforma-sabia pull request #498
Opened 2020-10-15 22:03 UTC by davioliveiira

## Summary

Resolves #491 

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2020-10-15 22:11 UTC, luizeboli requested changes
Top, simples e prático 🎉

Fiz 2 sugestões que considero importantes

2020-10-15 22:11 UTC, luizeboli commented on packages/web/components/Hero/styles.js
> +	const heroIndexImg = Math.floor(Math.random() * heroImgs.length);
```suggestion
	const heroIndexImg = Math.floor(Math.random() * heroImgs.length + 1);
```

Precisa somar o length do array + 1, se não você estará excluindo o último índice

2020-10-15 22:11 UTC, luizeboli commented on packages/web/components/Hero/styles.js
> +	return heroImgs[heroIndexImg || 0];
```suggestion
	return heroImgs[heroIndexImg];
```

Não precisa desse `|| 0`, já que o `Math.floor` vai arredondar pra baixo e o `Math.random` nunca vai retornar 1

2020-10-15 22:15 UTC, davioliveiira commented on packages/web/components/Hero/styles.js
> +	const heroIndexImg = Math.floor(Math.random() * heroImgs.length);
@luizeboli mas nesse caso o total ali seria 8 e não 7 (que é o valor do length do array). Assim ele não iria ficar tentando acessar o índice 8 do array? Cê não ta confundindo por conta do nome das imagens? hehehe

2020-10-15 22:16 UTC, davioliveiira commented on packages/web/components/Hero/styles.js
> +	return heroImgs[heroIndexImg || 0];
Boa @luizeboli !

2020-10-15 22:19 UTC, luizeboli commented on packages/web/components/Hero/styles.js
> +	const heroIndexImg = Math.floor(Math.random() * heroImgs.length);
@davioliveiira não, pois pensa no seguinte, o máximo que o `Math.random` retorna é 0.9999..

Agora, 0.999 * 8 é igual a 7.992..

O `Math.floor` sempre arredonda pro inteiro da casa anterior, ou seja, 7.99 vai virar 7.

Se você multiplicar apenas pela length do array, subtrai 1 dessa conta que eu fiz: 0.999 * 7 = 6.999, no floor vira 6. Assim, o último índice sempre é excluído

2020-10-15 22:43 UTC, davioliveiira commented on packages/web/components/Hero/styles.js
> +	const heroIndexImg = Math.floor(Math.random() * heroImgs.length);
Aah, agora entendi @luizeboli ! Alterei

2020-10-15 22:52 UTC, luizeboli approved these changes

2020-10-16 09:45 UTC, marcusmota approved these changes

2020-10-16 11:43 UTC, nichollasrennah commented
@davioliveiira pode fazer o merge.

2020-10-16 14:13 UTC, merged