Ajustar get dos response headers no fetch da curadoria
ufersa/plataforma-sabia pull request #508
Opened 2020-10-17 18:30 UTC by luizeboli

## Summary

Resolves #507

![Oct-17-2020 15-29-18](https://user-images.githubusercontent.com/13091635/96350760-9b7c9b80-108d-11eb-99b4-00cc3f52ac76.gif)

## QA Steps

1. Acessar tabela **Avaliar Tecnologias**
2. Testar os controles de paginação quando existirem mais de 5 resultados

## Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code passes the linting.
- [x] My code has proper inline documentation.
- [x] I have manually tested this PR.

2020-10-17 19:43 UTC, calaca requested changes
Paginação funcionando corretamente! Bom trabalho, @luizeboli !

![captured](https://user-images.githubusercontent.com/10481028/96352168-9cb2c600-1097-11eb-9dcc-04db0933985f.gif)
![image](https://user-images.githubusercontent.com/10481028/96352206-d4217280-1097-11eb-842e-601f3a71802d.png)

Só fica o pedido para adicionar um seed de tecnologias para já aparecerem listadas em "Avaliar Tecnologias". Atualmente temos que fazer essa população manualmente pelo banco e não é muito prático.

2020-10-18 12:01 UTC, marcusmota reviewed
Se puder fazer a sugestão da @calaca seria great! Tente popular com dados que façam um pouco de sentido

e.g "Título da tecnologia XXXXX" ao inves de utilizar o faker (se não for dar muito trabalho)

2020-10-18 19:46 UTC, lcnogueira approved these changes
"Topper" 👌

2020-10-18 21:21 UTC, luizeboli commented
@calaca @marcusmota alterei só o status das tecnologias pelo seed, era o mais simples.

2020-10-18 21:39 UTC, lcnogueira approved these changes

2020-10-19 23:13 UTC, calaca approved these changes
Mandou bem @luizeboli ! :100:

2020-10-19 23:13 UTC, calaca commented on packages/api/database/seeds/9_RevisionSeeder.js
> +
:clap:

2020-10-19 23:14 UTC, merged