Ajustar macro withParams para receber option e não efetuar o relacionamento
ufersa/plataforma-sabia pull request #535
Opened 2020-10-20 15:28 UTC by luizeboli

## Summary

Resolves #534

## Relevant technical choices

* Adicionei uma nova option no withParams, `skipRelationship`. Essa option permite excluir um relacionamento do `embed`, pois estava sobrescrevendo o `withFilters`

## QA Steps

* Executar testes funcionais

## Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code passes the linting.
- [x] My code has proper inline documentation.
- [x] I have manually tested this PR.

2020-10-20 16:00 UTC, NaylsonFerreira submitted a review, later dismissed

2020-10-20 23:26 UTC, alexandreadames approved these changes
Show!

2020-10-22 00:46 UTC, mateus4k commented on packages/api/app/Models/Traits/Params.js
> +			const { filterById = true, skipRelationship = [] } = options;
```suggestion
			const { filterById = true, skipRelationships = [] } = options;
```
Justificativa: é uma array 🙂

2020-10-22 00:48 UTC, alexandreadames commented on packages/api/app/Models/Traits/Params.js
> +			const { filterById = true, skipRelationship = [] } = options;
Cirurgico como sempre @mateus4k :1st_place_medal:

2020-10-22 00:52 UTC, mateus4k requested changes
O omi é bom!

2020-10-22 11:43 UTC, luizeboli commented
@mateus4k @alexandreadames dão aquela moral omis

2020-10-22 14:22 UTC, mateus4k approved these changes
O om é bom

2020-10-22 16:02 UTC, alexandreadames approved these changes
Boa @luizeboli

2020-10-23 14:14 UTC, NaylsonFerreira approved these changes

2020-10-23 17:06 UTC, merged