hotfix TecnologiesForm
ufersa/plataforma-sabia pull request #550
Opened 2020-10-25 14:52 UTC by NaylsonFerreira

## Summary

Resolves #510 

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2020-10-26 11:40 UTC, mateus4k commented on packages/admin/src/pages/technologies/Form/statusForm.js
> +					console.log(error.message);
```suggestion
```

2020-10-27 00:32 UTC, lcnogueira approved these changes
LGTM 👍

2020-10-27 00:39 UTC, lcnogueira commented
@NaylsonFerreira ,na verdade, eu tinha aprovado, mas vi aqui que tá falhando o CI.

2020-10-27 09:27 UTC, lcnogueira requested changes
@NaylsonFerreira ,na verdade, eu tinha aprovado, mas vi aqui que tá falhando o CI.

2020-10-27 13:32 UTC, luizeboli commented on packages/admin/src/pages/technologies/Form/statusForm.js
> +					{ id: 'published', name: 'Published' },
Não é interessante apresentar pro usuário as opções em português?

2020-10-27 14:05 UTC, NaylsonFerreira commented on packages/admin/src/pages/technologies/Form/statusForm.js
> +					{ id: 'published', name: 'Published' },
@nichollasrennah  ?

2020-10-28 16:20 UTC, NaylsonFerreira commented on packages/admin/src/pages/technologies/Form/statusForm.js
> +					{ id: 'published', name: 'Published' },
Não tenho certeza, porque não traduzimos conteúdos e não sei se esses status são considerados conteúdo.

2020-10-29 00:13 UTC, lcnogueira approved these changes
LGTM 👍

2020-10-29 00:36 UTC, luizeboli commented on packages/admin/src/pages/technologies/Form/statusForm.js
> +					{ id: 'published', name: 'Published' },
Tranquilo, faz sentido

2020-10-29 00:36 UTC, luizeboli approved these changes

2020-10-29 01:22 UTC, merged