Fix Show Technology Terms
ufersa/plataforma-sabia pull request #559
Opened 2020-10-27 00:24 UTC by alexandreadames

## Summary

Resolves #544 

## Relevant technical choices

Introduz o `skipPagination`, se `true` ele ignora a paginação do `HandleParams`

## QA Steps

`GET {{ base_url  }}/technologies/:id/terms?embed` e retonar todos os termos, metas e taxonomias.

## Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code passes the linting.
- [x] My code has proper inline documentation.
- [x] I have manually tested this PR.

2020-10-27 01:16 UTC, mateus4k requested changes
Show! Dá só uma olhada na situação que comentei 👇

2020-10-27 01:16 UTC, mateus4k commented on packages/api/app/Models/Traits/Params.js
>  				const { total } = countQuery[0];
Acho que isso aqui também só é feito caso necessite de paginação. Caso seja isso mesmo, coloca dentro do `if (!skipPagination)` logo abaixo

2020-10-27 19:00 UTC, marcusmota approved these changes
LGTM 👍 

working like a charm 

http://api-staging.plataformasabia.com/technologies/42/terms?embed

2020-10-27 20:46 UTC, alexandreadames commented on packages/api/app/Models/Traits/Params.js
>  				const { total } = countQuery[0];
@mateus4k eu deixei esse código fora porque, quando eu usar o `skipPagination` eu quero passar o total de registros `total` e `totalPages` para 
```javascript
request.params = {
					...request.params,
					total,
					totalPages,
				};
```
Sendo que totalPages = 1 e total será o total de registros, se eu tirar esses dois parâmetros vai null pra  `request.params`

2020-10-28 01:56 UTC, mateus4k commented on packages/api/app/Models/Traits/Params.js
>  				const { total } = countQuery[0];
Mas pra quê precisa desses parâmetros quando não se há paginação? 😅

2020-10-28 02:14 UTC, mateus4k commented
Aprovarei mas dá uma olhada aqui: https://github.com/ufersa/plataforma-sabia/pull/559#discussion_r513133567
Caso seja uma melhoria a se fazer, podemos abrir a issue pra fazermos depois, já que esse `skipPagination` raramente será usado, imagino! 👍

2020-10-28 02:14 UTC, mateus4k approved these changes

2020-10-28 12:07 UTC, merged