Adicionar videos na aba de mapas e anexos
ufersa/plataforma-sabia pull request #562
Opened 2020-10-28 00:54 UTC by davioliveiira

## Summary

Resolves #478

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2020-11-06 11:04 UTC, calaca submitted a review, later dismissed
Consegui adicionar os vídeos como indicado na PR com os três tipos de link:

![image](https://user-images.githubusercontent.com/10481028/98358608-bba4d800-2005-11eb-810d-83cd9596d353.png)

![image](https://user-images.githubusercontent.com/10481028/98358962-3ec62e00-2006-11eb-8694-53d0a53237cd.png)

![image](https://user-images.githubusercontent.com/10481028/98359215-995f8a00-2006-11eb-830f-1d80a8fecc10.png)

Apenas como ponto de melhoria, acho que seria interessante dar um feedback para o usuário quando uma URL com formato inválido é inserida. Atualmente apenas nada acontece e isso pode gerar uma experiência ruim. Creio que só um erro de input, nos padrões do que já usamos nos demais pontos do projeto, indicando que o formato da URL é inválido, já ajudaria bastante. O que acha?

De resto, por mim está perfeito!

Vou deixar aprovado no caso de deixarmos esse ponto de melhoria para outro momento.

2020-11-06 13:14 UTC, davioliveiira commented
> Consegui adicionar os vídeos como indicado na PR com os três tipos de link:
> 
> ![image](https://user-images.githubusercontent.com/10481028/98358608-bba4d800-2005-11eb-810d-83cd9596d353.png)
> 
> ![image](https://user-images.githubusercontent.com/10481028/98358962-3ec62e00-2006-11eb-8694-53d0a53237cd.png)
> 
> ![image](https://user-images.githubusercontent.com/10481028/98359215-995f8a00-2006-11eb-830f-1d80a8fecc10.png)
> 
> Apenas como ponto de melhoria, acho que seria interessante dar um feedback para o usuário quando uma URL com formato inválido é inserida. Atualmente apenas nada acontece e isso pode gerar uma experiência ruim. Creio que só um erro de input, nos padrões do que já usamos nos demais pontos do projeto, indicando que o formato da URL é inválido, já ajudaria bastante. O que acha?
> 
> De resto, por mim está perfeito!
> 
> Vou deixar aprovado no caso de deixarmos esse ponto de melhoria para outro momento.

Boa observação, vou implementar!

2020-11-06 13:36 UTC, luizeboli approved these changes
Did some small improvements, tell me if you agree 👍 

I agree with @calaca about feedback

2020-11-06 21:46 UTC, nichollasrennah commented
@calaca já aceitou as mudanças?

2020-11-07 00:58 UTC, calaca commented
> @calaca já aceitou as mudanças?

Com relação as alreações que o @luizeboli fez por mim tudo ok.

@davioliveiira vc vai implementar a sugestão que fiz nessa issue mesmo? Espero ela pra aprovar a tarefa?

PS: tem um conflito num snapshot

2020-11-11 11:12 UTC, nichollasrennah commented
O que falta pra terminar essa aqui @davioliveiira ?

2020-11-11 11:39 UTC, davioliveiira commented
> O que falta pra terminar essa aqui @davioliveiira ?

Opa @nichollasrennah ! Estou resolvendo os conflitos e adicionando o feedback que a @calaca sugeriu e já solicito nova revisão para aprovação

2020-11-12 12:50 UTC, luizeboli requested changes
Parabéns pelo trampo @davioliveiira, incrível..

Só sugeri algumas correções de acentuação, fora isso, perfeito.

Tenho uma dúvida também:

Se repararmos, a sessão de vídeo é a única que difere a estilização das demais (fundo branco, não ocupa 100%, e etc). Isso foi planejado dessa forma mesmo?

![image](https://user-images.githubusercontent.com/13091635/98942258-83513e00-24cc-11eb-8f75-81b8a3a39886.png)

2020-11-12 12:50 UTC, luizeboli commented on packages/web/components/Technology/Details/Tabs/Attachments.js
> +					<p>Nenhum video cadastrado</p>
```suggestion
					<p>Nenhum vídeo cadastrado</p>
```

Typo 😄

2020-11-12 12:50 UTC, luizeboli commented on packages/web/components/Technology/Details/Tabs/Attachments.js
> +				<UploadsTitle>Videos da Tecnologia</UploadsTitle>
```suggestion
				<UploadsTitle>Vídeos da Tecnologia</UploadsTitle>
```

Typo 😄

2020-11-12 12:50 UTC, luizeboli commented on packages/web/components/Technology/Details/Videos.js
> +					<img src={video.thumbnail} alt={`Youtube video ${video.videoId}`} />
```suggestion
					<img src={video.thumbnail} alt={`Youtube vídeo ${video.videoId}`} />
```

GG

2020-11-12 12:50 UTC, luizeboli commented on packages/web/components/TechnologyForm/MapAndAttachments/index.js
> +				form.setError('link_video', 'manual', 'O video já foi adicionado');
```suggestion
				form.setError('link_video', 'manual', 'O vídeo já foi adicionado');
```

Typo

2020-11-12 12:50 UTC, luizeboli commented on packages/web/components/TechnologyForm/MapAndAttachments/index.js
> +												alt={`Youtube video ${video.videoId}`}
```suggestion
												alt={`Youtube vídeo ${video.videoId}`}
```

Typo

2020-11-12 12:50 UTC, luizeboli commented on packages/web/components/TechnologyForm/MapAndAttachments/index.js
> +								<p>Nenhum video adicionado</p>
```suggestion
								<p>Nenhum vídeo adicionado</p>
```

2020-11-12 12:50 UTC, luizeboli commented on packages/web/components/TechnologyForm/Review/index.js
> +								<p>Nenhum video cadastrado</p>
```suggestion
								<p>Nenhum vídeo cadastrado</p>
```

Typo

2020-11-12 14:27 UTC, davioliveiira commented
> Parabéns pelo trampo @davioliveiira, incrível..
> 
> Só sugeri algumas correções de acentuação, fora isso, perfeito.
> 
> Tenho uma dúvida também:
> 
> Se repararmos, a sessão de vídeo é a única que difere a estilização das demais (fundo branco, não ocupa 100%, e etc). Isso foi planejado dessa forma mesmo?
> 
> ![image](https://user-images.githubusercontent.com/13091635/98942258-83513e00-24cc-11eb-8f75-81b8a3a39886.png)

Valeu o review @luizeboli ! Quanto ao visual, o @JoaoPauloSMoura que sugeriu dessa forma e inclusive ele até colocou no nosso figma

2020-11-13 17:19 UTC, luizeboli submitted a review, later dismissed

2020-11-13 20:07 UTC, luizeboli approved these changes

2020-11-13 20:24 UTC, calaca approved these changes
Mandou bem, @davioliveiira ! :100: 

![image](https://user-images.githubusercontent.com/10481028/99117745-0a89d900-25d5-11eb-8710-3cbfa55c545b.png)

2020-11-13 20:32 UTC, merged