Feature/web/checks be a curator
ufersa/plataforma-sabia pull request #594
Opened 2020-11-02 00:56 UTC by calaca

## Summary

Resolves #576 

![Peek 2020-11-01 21-00](https://user-images.githubusercontent.com/10481028/97820252-11872200-1c8c-11eb-88ea-c33fb60ec8e2.gif)

## Relevant technical choices

## QA Steps

1. Login as a user that can request to be a reviewer
2. Go to the user's profile
3. Click "be a reviewer" button
4. Verify that you can submit the form only if there is at least one category + subcategory selected and all checkboxes are checked

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2020-11-02 02:20 UTC, luizeboli commented
Hey @calaca, theres some snapshots outdated

2020-11-02 13:25 UTC, calaca commented
> Hey @calaca, theres some snapshots outdated

@luizeboli thanks for the heads up! I haven't noticed that.

2020-11-03 13:30 UTC, luizeboli commented on packages/web/components/Modal/BeAReviewerModal/index.js
> +
```suggestion
	const handleAcceptedTerms = (type) => {
		const types = Object.keys(acceptedTerms);

		if (!type || !types.some((item) => item === type)) {
			return null;
		}

		return setAcceptedTerms({
			...acceptedTerms,
			[type]: !acceptedTerms[type],
		});
	};

```

There's no need to disable this rule, just return

2020-11-03 13:34 UTC, luizeboli requested changes
Great @calaca 😃 

Did some comments, check it out

2020-11-03 13:34 UTC, luizeboli commented on packages/web/components/Modal/BeAReviewerModal/index.js
> +
```suggestion
	const handleAcceptedTerms = (type) => {
		const types = Object.keys(acceptedTerms);

		if (!type || !types.some((item) => item === type)) {
			return null;
		}

		return setAcceptedTerms({
			...acceptedTerms,
			[type]: !acceptedTerms[type],
		});
	};

```

There's no need to disable this rule, just return

2020-11-03 13:34 UTC, luizeboli commented on packages/web/components/Modal/BeAReviewerModal/index.js
> +						avaliar.
```suggestion
						Declaro que NÃO POSSUO conflito de interesses de ordens financeira,
						comercial, política, acadêmica e pessoal com as tecnologias pelas quais irei
						avaliar.
```

2020-11-03 13:34 UTC, luizeboli commented on packages/web/components/Modal/BeAReviewerModal/index.js
> +						extracontratual e adoção das medidas penais aplicáveis ao caso, conforme os{' '}
```suggestion
						Declaro que irei atender aos princípios éticos no uso da Plataforma Sabiá e
						desempenharei as minhas funções com probidade, boa-fé e de acordo com a
						legislação vigente, sendo inteiramente responsável pelas condutas lesivas a
						direitos de terceiros, ao próprio serviço disponibilizado pela plataforma e
						à Administração Pública, com responsabilização civil contratual e/ou
						extracontratual, e adoção das medidas penais aplicáveis ao caso, conforme os{' '}
```

2020-11-03 13:36 UTC, luizeboli commented on packages/web/components/Modal/BeAReviewerModal/index.js
> +						extracontratual e adoção das medidas penais aplicáveis ao caso, conforme os{' '}
```suggestion
						Declaro que irei atender aos princípios éticos no uso da Plataforma Sabiá e
						desempenharei as minhas funções com probidade, boa-fé e de acordo com a
						legislação vigente, sendo inteiramente responsável pelas condutas lesivas a
						direitos de terceiros, ao próprio serviço disponibilizado pela plataforma e
						à Administração Pública, com responsabilização civil contratual e/ou
						extracontratual, e adoção das medidas penais aplicáveis ao caso, conforme os{' '}
```

Improving grammar

2020-11-04 01:22 UTC, lcnogueira approved these changes
Hey, Lorena! You rock! 👩‍🎤

2020-11-04 01:22 UTC, lcnogueira commented on packages/web/components/Modal/BeAReviewerModal/index.js
> +			[type]: !acceptedTerms[type],
👌

2020-11-04 01:22 UTC, lcnogueira commented on packages/web/components/Modal/BeAReviewerModal/index.js
> +				}
👌

2020-11-04 13:33 UTC, luizeboli approved these changes

2020-11-05 11:41 UTC, merged