Technology cannot be distributed to related users
ufersa/plataforma-sabia pull request #612
Opened 2020-11-06 00:19 UTC by alexandreadames

## Summary

Resolves #606

## Relevant technical choices

Usuários relacionados a tecnologia são excluidos do processo de distribuição.

## QA Steps

`adonis test --files test/unit/technology-distribution.spec.js`

## Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code passes the linting.
- [x] My code has proper inline documentation.
- [x] I have manually tested this PR.

2020-11-06 02:24 UTC, mateus4k requested changes
💯 , somente alguns pequenos ajustes 😉

2020-11-06 02:24 UTC, mateus4k commented on packages/api/app/Utils/technology_distribution.js
> +	const technologyRelatedUsers = await technology.users().fetch();
Tenta fazer o select aqui pra não puxarmos tantos dados desnecessários.

```suggestion
	const technologyRelatedUsers = await technology.users().select('id').fetch();
```

2020-11-06 02:24 UTC, mateus4k commented on packages/api/app/Utils/technology_distribution.js
> +	const technologyRelatedUsersIds = technologyRelatedUsers.rows.map((user) => user.id);
Dando um `.toJSON()` após o `.fetch()` não vamos precisar acessar o `.rows` 😃

2020-11-06 12:51 UTC, marcusmota submitted a review, later dismissed

2020-11-07 00:15 UTC, alexandreadames commented on packages/api/app/Utils/technology_distribution.js
> +	const technologyRelatedUsersIds = technologyRelatedUsers.rows.map((user) => user.id);
O `.toJSON()` após o `.fetch()` não funciona, só dá certo mesmo com `.rows`

2020-11-07 00:18 UTC, mateus4k approved these changes
💯 é pouco, te dou é um 200!!! 🚀🚀

2020-11-07 00:20 UTC, marcusmota approved these changes

2020-11-07 00:44 UTC, merged