problema do delete de upload
ufersa/plataforma-sabia pull request #650
Opened 2020-11-17 16:13 UTC by mateus4k

## Summary

Resolves #557

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2020-11-18 12:29 UTC, luizeboli requested changes
It breaks when refreshing migrations

![image](https://user-images.githubusercontent.com/13091635/99530743-7925b880-2980-11eb-9d72-7582418e27ed.png)

2020-12-01 17:03 UTC, mateus4k commented
Atualizei os QA Steps na descrição.

2020-12-01 17:56 UTC, NaylsonFerreira commented
> Atualizei os QA Steps na descrição. É importante que se atentem a isso também :D

Então eh bom adicionar um teste para isso.

2020-12-02 12:38 UTC, luizeboli approved these changes

2020-12-02 12:39 UTC, merged