O admin deve visualizar todas as tecnologias independente do status
ufersa/plataforma-sabia pull request #662
Opened 2020-11-21 16:40 UTC by NaylsonFerreira

## Summary

Resolves #660 

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2020-11-22 13:13 UTC, NaylsonFerreira commented on packages/api/app/Controllers/Http/TechnologyController.js
> +		return technologies
Entendi, você já tá preparando para o reuso. @mateus4k
show!!

2020-11-22 18:20 UTC, alexandreadames requested changes

2020-11-22 18:20 UTC, alexandreadames commented on packages/api/test/functional/params.spec.js
>  test('GET list of Technologies without parameters', async ({ client }) => {
@NaylsonFerreira adapte os testes ao novo queryscope.

2020-11-22 18:31 UTC, NaylsonFerreira commented on packages/api/test/functional/params.spec.js
>  test('GET list of Technologies without parameters', async ({ client }) => {
Entendido.

2020-11-23 00:24 UTC, NaylsonFerreira commented on packages/api/app/Controllers/Http/TechnologyController.js
> +		return technologies
o eslint pega esse erro "no-unsafe-finally"

2020-11-24 11:33 UTC, mateus4k reviewed
1. Ficou show a nova implementação. Parabéns! 🎉 
2. O CI está falhando, pode dar uma olhada?
3. O método show continua funcionando normalmente com as mesmas regras do index?

2020-11-24 14:45 UTC, NaylsonFerreira commented
> 1. Ficou show a nova implementação. Parabéns! 🎉
> 2. O CI está falhando, pode dar uma olhada?
> 3. O método show continua funcionando normalmente com as mesmas regras do index?

Não consegui resolver o erro no cypress, Tem uma sugestão? 
Só falta isso pra fechar essa PR

2020-11-24 22:46 UTC, NaylsonFerreira commented
acho que está relacionada #665

2020-11-24 23:02 UTC, alexandreadames approved these changes
Bom trabalho!

2020-11-25 00:02 UTC, mateus4k approved these changes

2020-11-25 00:03 UTC, merged