Enable and disable a technology
ufersa/plataforma-sabia pull request #669
Opened 2020-11-26 02:21 UTC by mateus4k

## Summary

Resolves #572

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2020-12-17 23:39 UTC, calaca reviewed
Works like a charm and the code looks great! Well done @mateus4k ! :clap: 

I do think we should change the active icons:
![Peek 2020-12-17 20-11](https://user-images.githubusercontent.com/10481028/102554748-25ec7600-40a4-11eb-85c4-36aeddda808d.gif)
When we click on a technology to deactivate it, its icon is previously a red cross and when we do deactivate it, it's a green check mark. Shouldn't they be switched?

These icons made me think that they show the current active status of the listed technologies. It seems a bit confusing to have that icon related to the action instead of the technology status.

If it's decided to keep the icons related to the action, maybe something that could indicate both active on and off would be better imo.

And another suggestion:
![image](https://user-images.githubusercontent.com/10481028/102555230-20436000-40a5-11eb-93a0-2a123e8f86b4.png)
Wouldn't it look better like the image below?
![image](https://user-images.githubusercontent.com/10481028/102555310-4537d300-40a5-11eb-9e5d-68b0827423d2.png)

That's all!

2020-12-20 13:11 UTC, calaca commented on packages/web/components/Modal/DeleteModal/styles.js
> +				flex-direction: column;
Responsive is looking great now! :ok_hand:

2020-12-21 20:02 UTC, luizeboli requested changes
Many thanks for your effort 💪🏻 🎉 

I made some comments in addition to the need of changing activate/deactivate button to a switch

2020-12-22 00:34 UTC, alexandreadames requested changes
@mateus4k alguns pontos:
1. Pelo que eu entendi agora para uma tecnologia ser visível por qualquer usuário ou não estando logado ela precisa ser `published` e `active` certo? Nesse caso você precisa rever o middleware `Published`, sugiro que você: ou altere sua lógica ou migre tudo para o query scope `avaliable()`. As rotas que usam o middleware são:
`GET technologies/:id` 
`GET technologies/:id/terms`
`GET technologies/:id/users`
`GET technologies/:id/reviews`
2. Veja na minha PR os testes de tecnologias, muitas coisas que você fez aqui eu já tinha feito.
3. Eu senti falta de muitas coisas na sua documentação, veja o exemplo das minhas.

2020-12-22 00:34 UTC, alexandreadames commented on packages/api/start/routes/technologies.js
> + * @apiGroup Technologies
Inserir:
* @apiPermission UPDATE_TECHNOLOGY_ACTIVE

2020-12-22 00:34 UTC, alexandreadames commented on packages/api/start/routes/technologies.js
> + * @apiParam (Route Param) {Number} id Mandatory Technology ID
Inserir * @apiSuccess

2020-12-22 00:34 UTC, alexandreadames commented on packages/api/test/functional/technology.spec.js
> +		active: 0,
Assim dá certo? Não é necessário passar o data no factory? Assim:
```javascript
Factory.blueprint('App/Models/Technology', (faker,i,data) => {
	return {
		title: faker.sentence({ words: 3 }),
		description: faker.paragraph(),
		private: faker.bool(),
		likes: 0,
		patent: faker.bool(),
		patent_number: faker.string({ length: 8, alpha: true, numeric: true }),
		primary_purpose: faker.paragraph(),
		secondary_purpose: faker.paragraph(),
		application_mode: faker.paragraph(),
		application_examples: faker.paragraph(),
		installation_time: faker.integer({ min: 1, max: 800 }),
		solves_problem: faker.paragraph(),
		entailes_problem: faker.paragraph(),
		requirements: faker.paragraph(),
		risks: faker.paragraph(),
		contribution: faker.paragraph(),
		status:data.status,
		active: data.active,
		videos: JSON.stringify([
			{
				link: 'https://www.youtube.com/watch?v=8h7p88oySWY',
				videoId: '8h7p88oySWY',
				provider: 'Youtube',
				thumbnail: 'http://i3.ytimg.com/vi/8h7p88oySWY/hqdefault.jpg',
			},
		]),
	};
});
```

2020-12-22 02:14 UTC, mateus4k commented on packages/api/start/routes/technologies.js
> + * @apiParam (Route Param) {Number} id Mandatory Technology ID
É 204. No content :)

2020-12-22 02:15 UTC, mateus4k commented on packages/api/test/functional/technology.spec.js
> +		active: 0,
Não entendi teu ponto. Nesse caso eu criei a partir da factory porém com campos customizados para o teste.

2020-12-22 14:40 UTC, luizeboli approved these changes

2020-12-22 16:58 UTC, alexandreadames approved these changes
Show!

2020-12-22 16:58 UTC, alexandreadames commented on packages/api/database/migrations/1606357633943_add_active_column_to_technology_schema.js
> +				.defaultTo(false);
@mateus4k acredito que o valor default aqui seria `true`. Isso porque após todas as etapas de publicação da tecnologia o ADMIN vai mudar o status para `published`, porém se a tecnologia continuar active=false ela continua invisível, precisando que o próprio usuário a ative. Outra alternativa é no endpoint onde o ADMIN publica setar automaticamente para active=true.

2020-12-22 17:10 UTC, mateus4k commented on packages/api/database/migrations/1606357633943_add_active_column_to_technology_schema.js
> +				.defaultTo(false);
Muito bem observado. Obrigado!

2020-12-22 17:14 UTC, mateus4k commented
I feel it’s going to work out fine \o/

2020-12-22 17:16 UTC, alexandreadames approved these changes
Bom trabalho!

2020-12-22 17:16 UTC, luizeboli approved these changes

2020-12-22 17:27 UTC, merged