Sends Email in Background
ufersa/plataforma-sabia pull request #677
Opened 2020-11-26 22:03 UTC by alexandreadames

## Summary

Resolves #560

## Relevant technical choices

Todos os envios de email feitos pela API agora usam o Bull e Job de envio de emails;

## QA Steps

Testar no front os locais onde envia email e verificar que não há mais block;

## Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code passes the linting.
- [x] My code has proper inline documentation.
- [x] I have manually tested this PR.

2020-11-26 22:34 UTC, mateus4k commented on packages/api/app/Controllers/Http/AuthController.js
> +const Job = use('App/Jobs/SendMail');
O que acha de renomear para `SendMailJob`?

2020-11-26 22:40 UTC, mateus4k requested changes

2020-11-26 22:40 UTC, mateus4k commented on packages/api/test/functional/contact.spec.js
> +	await Bull.reset();
Assim como fiz aqui no `contact.spec.js`, pode adequar os demais testes para verificar se o Bull foi usado corretamente no teste?

Lembrando que precisará usar o `reset()` no começo de cada um. Ele não é async mas coloquei o `await` aí pra previnir que o teste vire um flaky.

Se puder testar sem nenhum `await` pro `reset`, ótimo!

2020-11-27 04:26 UTC, NaylsonFerreira commented on packages/api/test/functional/contact.spec.js
> +	await Bull.reset();
Pode pensar em uma função utilitária que faz o reset e toda essa comparação.
```
const bullCall = Bull.spy.calls[0];
assert.equal('add', bullCall.funcName);
assert.equal(payload.message, bullCall.args[1].message);
assert.isTrue(Bull.spy.called);
```

2020-11-28 11:39 UTC, mateus4k commented on packages/api/test/functional/contact.spec.js
> +	await Bull.reset();
Poderia ser, mas, ficaria muito rígido. Qualquer alteração mínima a função já não serviria, ou seja, otimização prematura :/

2020-11-28 12:10 UTC, mateus4k approved these changes
💯

2020-11-28 12:47 UTC, NaylsonFerreira approved these changes

2020-11-28 12:47 UTC, NaylsonFerreira commented on packages/api/test/unit/technology-distribution.spec.js
> +	/* const bullCall = Bull.spy.calls[0];
Acho que esqueceu esses comentários aqui

2020-11-28 12:52 UTC, mateus4k commented on packages/api/test/unit/technology-distribution.spec.js
> +	/* const bullCall = Bull.spy.calls[0];
Bem observado!

2020-11-28 12:56 UTC, mateus4k requested changes
Ajeitar o teste de distribuição de tecnologias para revisão

2020-11-28 17:02 UTC, NaylsonFerreira approved these changes
LGTM

2020-11-28 19:07 UTC, mateus4k approved these changes

2020-11-28 19:29 UTC, merged