Integrates questions API with front
ufersa/plataforma-sabia pull request #685
Opened 2020-11-30 14:12 UTC by calaca

## Summary

Resolves #531 

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2020-12-07 15:20 UTC, luizeboli requested changes
Awesome, great job :tada: 

I made one comment here in addition to the video I sent you in Slack

2020-12-07 15:20 UTC, luizeboli commented on packages/web/components/Technology/Details/Tabs/FAQ/index.js
> +		mutate('get-technology-answered-questions');
You don't need to pass key here as this mutate is already bound to that query

See https://swr.vercel.app/docs/mutation#bound-mutate

2020-12-08 12:53 UTC, luizeboli commented on packages/web/components/UserProfile/UserProfile.js
> +		revalidateOnFocus: true,
Focus revalidation is true by default 😄

2020-12-08 13:02 UTC, luizeboli approved these changes
Nice work done 🥳

2020-12-10 00:45 UTC, lcnogueira approved these changes
Can confirm it's working as expected. Great job, @calaca !

2020-12-10 00:45 UTC, lcnogueira commented on packages/web/components/Technology/Details/Tabs/FAQ/index.js
> +							<S.LoadMoreButton
This load more feature is awesome! 👏

2020-12-10 01:25 UTC, merged