Feature/api/idea database
ufersa/plataforma-sabia pull request #688
Opened 2020-12-01 20:02 UTC by alexandreadames

## Summary

Resolves #537

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2020-12-04 12:08 UTC, NaylsonFerreira approved these changes
Padrão... Padrão... 👌

2020-12-04 22:45 UTC, mateus4k commented on packages/api/database/migrations/1606773532660_idea_schema.js
> +				.inTable('users');
Faltou o onUpdate e onDelete

2020-12-04 22:48 UTC, mateus4k requested changes
Good job, man! 👊

2020-12-04 22:48 UTC, mateus4k commented on packages/api/database/migrations/1606773532660_idea_schema.js
> +				.inTable('users');
Faltou o onUpdate e onDelete

2020-12-05 14:33 UTC, mateus4k approved these changes

2020-12-05 14:35 UTC, mateus4k commented
Se lembre de aplicar a mudança que comenteia

2020-12-05 15:02 UTC, alexandreadames commented on packages/api/app/Validators/StoreIdea.js
> +			keywords: 'array|required',
@NaylsonFerreira nesse caso ele aceita number(id) ou string(term slug), você sabe como especificar dois tipos ao mesmo tempo? Eu testei fazer assim `keywords.*: string|number`, mas nessse caso ele dá problema que não seria um ou outro e sim um e outro.

2020-12-05 15:03 UTC, mateus4k submitted a review, later dismissed

2020-12-09 03:49 UTC, NaylsonFerreira commented
Falta ver os testes que falharam

2020-12-09 03:55 UTC, NaylsonFerreira commented on packages/api/app/Validators/StoreIdea.js
> +			keywords: 'array|required',
Não sei como fazer pra checar os dois.
Imaginei que seria só inteiros

2020-12-09 19:56 UTC, NaylsonFerreira approved these changes

2020-12-14 14:24 UTC, mateus4k approved these changes

2020-12-14 14:34 UTC, merged