Model and migrations
ufersa/plataforma-sabia pull request #689
Opened 2020-12-02 00:56 UTC by alexandreadames

## Summary

Resolves #687 

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2020-12-09 03:46 UTC, NaylsonFerreira submitted a review, later dismissed
LGTM

2020-12-09 21:39 UTC, NaylsonFerreira submitted a review, later dismissed

2020-12-17 12:33 UTC, mateus4k commented
Please resolve conflicts

2020-12-17 12:56 UTC, mateus4k requested changes

2020-12-17 12:56 UTC, mateus4k commented on packages/api/test/functional/announcement.spec.js
> +		})
Vc pode substituir isso por um `const announcement = await Factory.model('App/Models/Announcement').make();`
```suggestion
		.send(announcement.toJSON())
```

2020-12-17 12:56 UTC, mateus4k commented on packages/api/test/functional/announcement.spec.js
> +	response.body.status = announcementStatuses.PENDING;
Pq isso? 🤔🤔🤔

2020-12-17 12:56 UTC, mateus4k commented on packages/api/test/functional/announcement.spec.js
> +test('DELETE /announcements/:id deletes an announcements', async ({ client, assert }) => {
```suggestion
test('DELETE /announcements/:id deletes an announcement', async ({ client, assert }) => {
```

2020-12-18 22:52 UTC, alexandreadames commented on packages/api/test/functional/announcement.spec.js
> +	response.body.status = announcementStatuses.PENDING;
Rapaz é porque quando eu busco o announcementCreated não vem o status

2020-12-21 16:34 UTC, NaylsonFerreira approved these changes

2020-12-21 16:34 UTC, NaylsonFerreira commented on packages/api/app/Models/Announcement.js
> +			if (keywordsList && keywordsList.length) {
```suggestion
			const keywordsList = filters?.keywords.split(',') || [];
			if (keywordsList?.length) {
```

2020-12-21 16:34 UTC, NaylsonFerreira commented on packages/api/app/Models/Announcement.js
> +			if (targetAudiencesList && targetAudiencesList.length) {
```suggestion
			const targetAudiencesList = filters?.targetAudiences.split(',') || [];
			if (targetAudiencesList?.length) {
```

2020-12-21 16:34 UTC, NaylsonFerreira commented on packages/api/test/functional/announcement.spec.js
> +	);
```suggestion
	await Promise.all(
		publishedAnnouncements.map((announcement) => {
			announcement.status = announcementStatuses.PUBLISHED;
			return [
				announcement.user().associate(user),
				announcement.institution().associate(institution),
				announcement.save(),
			];
		}),
	);
```

2020-12-21 18:23 UTC, NaylsonFerreira approved these changes
Boas Festas!!

2020-12-22 03:41 UTC, NaylsonFerreira approved these changes

2020-12-23 17:34 UTC, mateus4k approved these changes

2020-12-23 18:20 UTC, merged