NProgress bar not shown when changing routes
ufersa/plataforma-sabia pull request #692
Opened 2020-12-02 20:29 UTC by luizeboli

## Summary

Resolves #691 

## QA Steps

1. Access application home page
2. Navigate between pages
3. Progress bar must be shown in top of header

## Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code passes the linting.
- [x] My code has proper inline documentation.
- [x] I have manually tested this PR.

2020-12-02 20:34 UTC, mateus4k requested changes

2020-12-02 20:34 UTC, mateus4k commented on packages/web/styles/global.js
> +		z-index: 1100;
É melhor ajeitar logo de uma vez e usar 1, 2, 3... 🤣

2020-12-02 20:40 UTC, mateus4k approved these changes

2020-12-03 09:14 UTC, lcnogueira approved these changes

2020-12-03 13:13 UTC, merged