Cadastro de organizações no ADMIN
ufersa/plataforma-sabia pull request #697
Opened 2020-12-09 14:31 UTC by NaylsonFerreira

## Summary

Resolves #690

Adicionar, Visualizar,Editar e Excluir uma organização no ADMIN.

## Relevant technical choices

## QA Steps

1 - Acessar o ambiente de administração
2 - Clicar em `Institutions` no menu esquerdo para listar todos as organizações
3 - Clicar em editar para alterar uma organização
4 - Clicar em apagar para deletar uma organização 
## Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code passes the linting.
- [x] My code has proper inline documentation.
- [x] I have manually tested this PR.

2020-12-09 21:50 UTC, alexandreadames requested changes
Muito bom!

2020-12-09 21:50 UTC, alexandreadames commented on packages/api/app/Models/Institution.js
> +	user_id() {
@NaylsonFerreira não seria melhor só `user()`?, acredito que não tem problema.

2020-12-09 21:50 UTC, alexandreadames commented on packages/api/app/Models/Permission.js
>  			}
```suggestion
			if (institution.user_id !== user.id) return false
```

2020-12-09 21:50 UTC, alexandreadames commented on packages/api/test/functional/institution.spec.js
>  test('PUT /institutions/:id updates an institution', async ({ client, assert }) => {
@NaylsonFerreira por favor inclua os testes que verificam se as permissões estão bloqueando usuários não autorizados. Crie mais dois testes: update e delete, Ex:

```javascript
test('PUT /questions/:id/answer returns an error if the user is not authorized', async ({
	client,
}) => {
	const { user } = await createUser({ append: { status: 'verified' } });
	const { user: owner } = await createUser();
	const { user: asker } = await createUser();
	const technology = await Factory.model('App/Models/Technology').create();
	await technology.users().attach(owner.id);
	const answer = 'My favourite is warm weather ';

	const question = await Factory.model('App/Models/TechnologyQuestion').create();

	await question.technology().associate(technology);
	await question.user().associate(asker);

	const response = await client
		.put(`/questions/${question.id}/answer`)
		.loginVia(user, 'jwt')
		.send({
			answer,
		})
		.end();

	response.assertStatus(403);
	response.assertJSONSubset(
		errorPayload(errors.UNAUTHORIZED_ACCESS, antl('error.permission.unauthorizedAccess')),
	);
});
```

2020-12-09 21:50 UTC, alexandreadames commented on packages/api/app/Controllers/Http/InstitutionController.js
>  		return response.status(201).send({ institution });
Seria interessante adotar esse padrão na API.

2020-12-10 09:55 UTC, NaylsonFerreira commented on packages/api/app/Models/Institution.js
> +	user_id() {
Nesse caso preciso criar uma migration certo?
Voce acha melhor chamar esse campo de **user** , **owner** ou **responsible** ?
Pelo que entendi esse campo seria o usuário que cadastrou a instituição

2020-12-10 16:26 UTC, alexandreadames commented on packages/api/app/Models/Institution.js
> +	user_id() {
Esse campo já existe na migration, aqui seria apenas uma convenção de funções, fica muito estranho uma função `user_id()`.

2020-12-10 19:10 UTC, NaylsonFerreira commented on packages/api/app/Models/Institution.js
> +	user_id() {
Entendi.
Coloquei como **responsible** e mapei no modelo.

2020-12-10 23:27 UTC, calaca requested changes
Tudo certo com o código, a edição e criação de instituição. :clap: 

Porém quando vou deletar uma instituição, o seguinte erro é apresentado como notificação:
![image](https://user-images.githubusercontent.com/10481028/101841321-74d66080-3b24-11eb-93d6-54317569ec8c.png)

E os seguintes erros são apresentados no console:
![Peek 2020-12-10 20-11](https://user-images.githubusercontent.com/10481028/101841148-26c15d00-3b24-11eb-93a2-93f551b231b2.gif)

Por fim, o item não some da listagem, só some quando atualizamos a página.

Só consertar essa funcionalidade mesmo.

2020-12-11 15:24 UTC, NaylsonFerreira commented
> Tudo certo com o código, a edição e criação de instituição. 👏
> 
> Porém quando vou deletar uma instituição, o seguinte erro é apresentado como notificação:
> ![image](https://user-images.githubusercontent.com/10481028/101841321-74d66080-3b24-11eb-93d6-54317569ec8c.png)
> 
> E os seguintes erros são apresentados no console:
> ![Peek 2020-12-10 20-11](https://user-images.githubusercontent.com/10481028/101841148-26c15d00-3b24-11eb-93a2-93f551b231b2.gif)
> 
> Por fim, o item não some da listagem, só some quando atualizamos a página.
> 
> Só consertar essa funcionalidade mesmo.

Pode olhar novamente?

2020-12-11 18:21 UTC, luizeboli approved these changes
LGTM 👍🏻  🎉

2020-12-11 21:48 UTC, calaca approved these changes
Tudo certo!
Mandou bem @NaylsonFerreira !

2020-12-11 22:06 UTC, alexandreadames approved these changes
Bom trabalho!

2020-12-11 22:08 UTC, merged