Gestão do Banco de Ideias no ADMIN
ufersa/plataforma-sabia pull request #712
Opened 2020-12-17 16:17 UTC by NaylsonFerreira

## Summary

Resolves #686

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2020-12-17 22:38 UTC, calaca requested changes
Listagem e edição de ideia funcionando perfeitamente! :clap: 

@NaylsonFerreira só notei que a exclusão não está funcionando. Criei uma ideia nova, editei e depois tentei exlcuir. Nesse último passo, é apresentado a notificação "unauthorized" e o erro 401 no console:
![image](https://user-images.githubusercontent.com/10481028/102550833-4a911f80-409d-11eb-842a-5ed08507cfde.png)

PS: estou logada com a conta `sabiatestingadmin` e essa conta é a dona da ideia

2020-12-17 22:38 UTC, calaca commented on packages/admin/src/pages/ideas/Form/index.js
> +const IdeassForm = ({ record, save, resource }) => {
Typo aqui com dois "s" em "ideas" :eyes:

2020-12-17 22:38 UTC, calaca commented on packages/admin/src/pages/ideas/create.js
> +const IdeassCreate = ({ resource, basePath }) => (
Mesmo typo indicado acima.

2020-12-17 22:38 UTC, calaca commented on packages/admin/src/pages/ideas/edit.js
> +const IdeassEdit = ({ basePath, id, resource }) => (
Mesmo typo indicado acima.

2020-12-17 22:38 UTC, calaca commented on packages/admin/src/pages/ideas/list.js
> +const IdeassList = ({ basePath, resource, hasCreate, hasEdit, hasList, hasShow }) => (
Mesmo typo indicado acima.

2020-12-18 13:34 UTC, NaylsonFerreira commented
> Listagem e edição de ideia funcionando perfeitamente! 👏
> 
> @NaylsonFerreira só notei que a exclusão não está funcionando. Criei uma ideia nova, editei e depois tentei exlcuir. Nesse último passo, é apresentado a notificação "unauthorized" e o erro 401 no console:
> ![image](https://user-images.githubusercontent.com/10481028/102550833-4a911f80-409d-11eb-842a-5ed08507cfde.png)
> 
> PS: estou logada com a conta `sabiatestingadmin` e essa conta é a dona da ideia

Você rodou as migration e as seeds antes do teste?
Aqui funcionou, vou investigar mais um pouco.

2020-12-19 12:09 UTC, calaca commented
> > Listagem e edição de ideia funcionando perfeitamente! clap
> > @NaylsonFerreira só notei que a exclusão não está funcionando. Criei uma ideia nova, editei e depois tentei exlcuir. Nesse último passo, é apresentado a notificação "unauthorized" e o erro 401 no console:
> > ![image](https://user-images.githubusercontent.com/10481028/102550833-4a911f80-409d-11eb-842a-5ed08507cfde.png)
> > PS: estou logada com a conta `sabiatestingadmin` e essa conta é a dona da ideia
> 
> Você rodou as migration e as seeds antes do teste?
> Aqui funcionou, vou investigar mais um pouco.

Sim! Até apaguei o banco todo e criei de novo.

2020-12-19 12:23 UTC, calaca approved these changes
Deletei o banco novamente e re-executei as migrations e seeds e a deleção de ideas funcionou!

Bom trabalho @NaylsonFerreira ! :100:

2020-12-19 12:23 UTC, calaca commented on packages/admin/src/pages/ideas/Form/index.js
> +const IdeasForm = ({ record, save, resource }) => {
:clap:

2020-12-21 20:19 UTC, luizeboli approved these changes
LGTM 👍🏻 

Bom trabalho :)

2020-12-21 20:38 UTC, merged