Create ideas bank page
ufersa/plataforma-sabia pull request #727
Opened 2020-12-23 01:59 UTC by calaca

## Summary

Resolves #537 

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2021-01-26 13:27 UTC, luizeboli requested changes
Wow, awesome job @calaca 🎉 

I did some comments in order to improve usability.

1. What about adding a little bit more margin between these fields messages? So users better discern it.
![image](https://user-images.githubusercontent.com/13091635/105848912-681ba800-5fbe-11eb-805c-fecf44bba956.png)

2. After submitting a new idea only `Titúlo da ideia` input is cleared
![image](https://user-images.githubusercontent.com/13091635/105849137-c052aa00-5fbe-11eb-9417-e7b02a4c055f.png)

3. I've run `npm run algolia:index` command as I'm in a new environment, but when sorting by update or release date this error occurs:
![image](https://user-images.githubusercontent.com/13091635/105849515-43740000-5fbf-11eb-9e52-52fd8c544752.png)

Looking at Algolia dashboard these indexes really doesn't exists. Maybe you forgot to add?

2021-01-26 13:27 UTC, luizeboli commented on packages/web/utils/helper.js
> + * Handle phone number mask, necessary to alternate between masks when phone has 9 digits
Is this the true description? I'm confused due it's the same of `beforeMaskedValueChange` but seems to have another purpose 😅

2021-01-31 12:17 UTC, calaca commented
> Wow, awesome job @calaca 
> 
> I did some comments in order to improve usability.
> 
> 1. What about adding a little bit more margin between these fields messages? So users better discern it.
>    ![image](https://user-images.githubusercontent.com/13091635/105848912-681ba800-5fbe-11eb-805c-fecf44bba956.png)
> 2. After submitting a new idea only `Titúlo da ideia` input is cleared
>    ![image](https://user-images.githubusercontent.com/13091635/105849137-c052aa00-5fbe-11eb-9417-e7b02a4c055f.png)
> 3. I've run `npm run algolia:index` command as I'm in a new environment, but when sorting by update or release date this error occurs:
>    ![image](https://user-images.githubusercontent.com/13091635/105849515-43740000-5fbf-11eb-9e52-52fd8c544752.png)
> 
> Looking at Algolia dashboard these indexes really doesn't exists. Maybe you forgot to add?

Thanks for the review @luizeboli !

1. I've added that same input wrapper that exists around the title input to the other ones
2. I've managed to clear all other fields using `setValue` but it seems like there's a bug with `TextField` that applies the clean value then re-applies the old text. Maybe it should do into a separate issue as it happens at the separate contact page as well and every other place.
3. This error happens because these indexes don't exist in Algolia yet. Mateus said he'd be working on this as soon as he gets some time. But the front part of it is ready, we just need that data indexed by the API.

2021-01-31 23:44 UTC, luizeboli commented
@calaca theres a `reset` method exposed by `useForm`, but to make it work properly you must pass `defaultValues` to the form. So you can call `form.reset`, but, we're using the `Form` component. I couldn't expose this reset method using `useImperativeHandle`, because it's mandatory to pass a ref, doing things this way would break other parts.

2021-01-31 23:44 UTC, luizeboli submitted a review, later dismissed

2021-02-03 00:26 UTC, lcnogueira approved these changes

2021-02-03 00:26 UTC, lcnogueira commented on packages/web/components/LandingPage/About/index.js
> +import * as S from './styles';
I prefer that way too nowadays 👌

2021-02-03 01:22 UTC, luizeboli approved these changes

2021-02-04 00:09 UTC, merged