adding fields
ufersa/plataforma-sabia pull request #754
Opened 2021-01-15 16:36 UTC by NaylsonFerreira

## Summary

Resolves #750

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2021-01-15 17:13 UTC, alexandreadames requested changes
Dr. @NaylsonFerreira apenas duas observações:
1. Você deve usar um componente para selecionar as áreas da tecnologia conforme foi feito no web.(Pode ver com Dr. @luizeboli )
2. Você deve excluir o campo CATEGORY, pois ele não será mais usado por enquanto.

2021-01-15 17:26 UTC, NaylsonFerreira commented
> Dr. @NaylsonFerreira apenas duas observações:
> 
> 1. Você deve usar um componente para selecionar as áreas da tecnologia conforme foi feito no web.(Pode ver com Dr. @luizeboli )
> 2. Você deve excluir o campo CATEGORY, pois ele não será mais usado por enquanto.

Ele tá gerando um select para cada taxonomia, é só apagar a taxonomia do banco

2021-01-15 17:31 UTC, alexandreadames commented
> > Dr. @NaylsonFerreira apenas duas observações:
> > 
> > 1. Você deve usar um componente para selecionar as áreas da tecnologia conforme foi feito no web.(Pode ver com Dr. @luizeboli )
> > 2. Você deve excluir o campo CATEGORY, pois ele não será mais usado por enquanto.
> 
> Ele tá gerando um select para cada taxonomia, é só apagar a taxonomia do banco

Precisa ver com @nichollasrennah isso. Eu levantei essa questão, pode ser que a categoria possa ser usada para outro propósito no futuro.

2021-01-19 15:31 UTC, mateus4k submitted a review, later dismissed

2021-01-19 15:53 UTC, mateus4k approved these changes

2021-01-19 15:57 UTC, luizeboli approved these changes

2021-01-19 16:16 UTC, alexandreadames approved these changes
Bom trabalho!

2021-01-19 16:17 UTC, merged