Feature/api/device-token
ufersa/plataforma-sabia pull request #800
Opened 2021-02-02 21:35 UTC by alexandreadames

## Summary

Resolves #798 

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2021-02-10 11:22 UTC, mateus4k requested changes

2021-02-10 11:22 UTC, mateus4k commented on packages/api/app/Controllers/Http/DeviceTokenController.js
> +		return deviceTokens;
```suggestion
		return User.deviceTokens().fetch();
```

2021-02-10 11:22 UTC, mateus4k commented on packages/api/app/Controllers/Http/DeviceTokenController.js
> +		}
Isso pode ser um `exists` no validator 🤔

2021-02-10 11:22 UTC, mateus4k commented on packages/api/app/Controllers/Http/DeviceTokenController.js
> +		return deviceToken;
```suggestion
		return User.deviceTokens()
			.query()
			.where({ device_uuid: params.uuid })
			.first();
```

2021-02-10 11:22 UTC, mateus4k commented on packages/api/database/migrations/1612300913780_device_token_schema.js
> +				.inTable('users');
É interessante apagarmos os tokens ao excluirmos o usuário
```suggestion
				.inTable('users')
				.onUpdate('cascade')
				.onDelete('cascade');
```

2021-02-12 17:07 UTC, alexandreadames commented on packages/api/app/Controllers/Http/DeviceTokenController.js
> +		}
O ideal aqui seria criar uma permissão nova, mas eu quis simplificar. A lógica é não permitir que outro usuário atualize o token criado por outro.

2021-02-14 16:45 UTC, mateus4k submitted a review, later dismissed

2021-02-16 02:56 UTC, mateus4k commented
@alexandreadames please solve conflicts

2021-02-16 20:08 UTC, alexandreadames commented
> @alexandreadames please solve conflicts

Solved!

2021-02-17 00:53 UTC, mateus4k approved these changes

2021-02-21 22:53 UTC, mtullyoc approved these changes
Great!

2021-02-21 22:54 UTC, merged