Atualizar tecnologias no ADMIN
ufersa/plataforma-sabia pull request #807
Opened 2021-02-06 16:32 UTC by NaylsonFerreira

## Summary

Resolves #784

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2021-02-06 17:49 UTC, NaylsonFerreira commented
![787](https://user-images.githubusercontent.com/25301330/107125757-6ab5b180-688a-11eb-9587-799fb9f67307.png)

2021-02-07 12:29 UTC, mateus4k requested changes

2021-02-07 12:29 UTC, mateus4k commented on packages/api/app/Controllers/Http/TechnologyController.js
> +			})
Pode adicionar isso na documentação?

2021-02-07 12:29 UTC, mateus4k commented on packages/admin/src/pages/technologies/list.js
> +					const trl = terms?.filter(({ taxonomy_id }) => taxonomy_id === 4)[0];
É bom procurarmos outra maneira de filtrar esse TRL. Não é uma boa prática depender de IDs do banco. A qualquer momento eles podem mudar e isso quebraria este código.

E ao invés de um `filter()[0]` pode usar um `find()` 🙂

2021-02-07 13:19 UTC, alexandreadames requested changes
Por favor veja esse comportamento:

https://www.loom.com/share/5d4a99a0e6f74d95a1b3e4d6e2171d95

2021-02-07 13:23 UTC, alexandreadames submitted a review, later dismissed
Good job!

2021-02-07 13:28 UTC, NaylsonFerreira commented on packages/admin/src/pages/technologies/list.js
> +					const trl = terms?.filter(({ taxonomy_id }) => taxonomy_id === 4)[0];
Teria que fazer uma requisição com o slug da taxonomia e descobrir o id e depois filtrar

2021-02-07 13:39 UTC, mateus4k commented on packages/admin/src/pages/technologies/list.js
> +						const trl = terms?.find(({ taxonomy_id }) => taxonomy_id === stage.id);
Very well 👍

2021-02-07 15:37 UTC, alexandreadames requested changes

2021-02-07 15:37 UTC, alexandreadames commented on packages/admin/src/pages/technologies/list.js
> +					const trl = terms?.find(({ taxonomy_id }) => taxonomy_id === 4);
@NaylsonFerreira aqui não é interessante deixar o taxonomy_id === 4, acredito que o melhor seria fazer uma requisição para obter a taxonomia por slug.

2021-02-07 15:45 UTC, NaylsonFerreira commented on packages/admin/src/pages/technologies/list.js
> +					const trl = terms?.find(({ taxonomy_id }) => taxonomy_id === 4);
Eu fiz isso no último commit

2021-02-07 15:51 UTC, alexandreadames approved these changes
💯

2021-02-07 18:40 UTC, mateus4k approved these changes

2021-02-07 20:11 UTC, merged