Add thumbnail to service
ufersa/plataforma-sabia pull request #832
Opened 2021-02-13 16:49 UTC by alexandreadames

## Summary

Resolves #815 

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2021-02-13 19:57 UTC, mateus4k requested changes
Show de bola, @alexandreadames
Deixei somente um comentário 🙂

2021-02-13 19:57 UTC, mateus4k commented on packages/api/database/factory.js
> +		filename: `${faker.word({ length: 20 })}.${faker.pickone(['png', 'jpg', 'pdf'])}`,
```suggestion
		filename: `${faker.word({ length: 20 })}.${faker.pickone(Config.get('uploads.allowedFormats'))}`,
```

2021-02-15 12:51 UTC, mateus4k approved these changes

2021-02-15 13:24 UTC, NaylsonFerreira approved these changes

2021-02-15 13:24 UTC, merged