Atualização da aba ATTACHMENTS no cadastro de tecnologias em ADMIN
ufersa/plataforma-sabia pull request #833
Opened 2021-02-14 17:30 UTC by NaylsonFerreira

## Summary

Resolves #785

## Relevant technical choices

## QA Steps

* Acessar a aba ATTACHMENTS em tecnologias
* Enviar e apagar imagens e PDFs

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2021-02-14 17:37 UTC, mateus4k requested changes

2021-02-14 17:37 UTC, mateus4k commented on packages/admin/src/components/UploadInput.js
> +		setLoading(!!files.lenght);
```suggestion
		setLoading(!!files.length);
```

2021-02-14 17:45 UTC, mateus4k submitted a review, later dismissed

2021-02-16 13:35 UTC, mateus4k approved these changes

2021-02-16 21:57 UTC, alexandreadames approved these changes
Excelente trabalho 💯

2021-02-16 21:59 UTC, merged