initial feature
ufersa/plataforma-sabia pull request #895
Opened 2021-03-13 01:39 UTC by mateus4k

## Summary

Resolves #878

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2021-03-13 14:01 UTC, mateus4k commented on packages/web/components/Algolia/searchBox.js
> -							translations={{
I'm sorry for that, @luizeboli 😢

2021-03-15 11:37 UTC, luizeboli requested changes
Everything's working fine but Service's search.

You forgot to add Keywords filter to the sidebar:

![image](https://user-images.githubusercontent.com/13091635/111147756-96067d00-8569-11eb-97f2-be61a8b227cd.png)

Also added one comment \o/

2021-03-15 11:37 UTC, luizeboli commented on packages/api/app/Utils/Algolia/indexes/service.js
> +
`keywords` belongs to many solutions, what about move it to `core` or somewhere else so we can reuse easily?

2021-03-15 11:37 UTC, luizeboli commented on packages/api/app/Utils/Algolia/indexes/technology.js
> +
So we don't duplicate code heh

2021-03-19 12:44 UTC, luizeboli approved these changes
🎉

2021-03-19 12:47 UTC, merged