create message page
ufersa/plataforma-sabia pull request #958
Opened 2021-03-23 20:45 UTC by Pedro-Alcantara-M

## Summary

https://github.com/ufersa/plataforma-sabia/issues/943

Resolves #

## Relevant technical choices

## QA Steps

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code passes the linting.
- [ ] My code has proper inline documentation.
- [ ] I have manually tested this PR.

2021-03-23 20:55 UTC, Pedro-Alcantara-M commented
**Antes**

![antes2](https://user-images.githubusercontent.com/77678283/112217033-f6985880-8c00-11eb-815f-90c7d77fa8ce.png)


**Depois**

![depois2](https://user-images.githubusercontent.com/77678283/112217063-fef09380-8c00-11eb-9ebd-e5c81606fb23.png)

2021-03-23 21:19 UTC, luizeboli approved these changes
Top 👍🏻

2021-03-23 21:20 UTC, luizeboli requested changes

2021-03-23 21:20 UTC, luizeboli commented on packages/web/pages/user/my-account/messages.js
> +					<Maintanance />
O nome do componente ta escrito errado, seria `Maintenance`, reparei agora ;)

2021-03-24 01:45 UTC, luizeboli approved these changes

2021-03-24 12:48 UTC, mateus4k approved these changes

2021-03-24 13:01 UTC, merged